### ISSUE TITLE
2- Design the algorithm such that it takes the input of a transcript abundance data frame(symbol, sample, count, cell_type) and a specified hierarchy. (Find the file in cellsig) output nodal signatures.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#10]
In the github README, there is an example of the code of how to do this. I have done this for you.

before that, you should 
- install dev branch of tidybulk from github
- pull the update cellsig from github (do you commits first)
- reinstall cellsig (branch data-exploration)

**Comment by jianwu1** [comment]
> * reinstall cellsig (branch data-exploration)

Hi Stefano,

Can I ask how to reinstall cellsig? 

I tried this command:
` R CMD INSTALL --preclean --no-multiarch --with-keep.source ../cellsig`

But the error says **version `GLIBCXX_3.4.29' not found** (I searched for the error online but couldn't find anything helpful):

```
[wu.j@rstudio-2 cellsig]$ R CMD INSTALL --preclean --no-multiarch --with-keep.source ../cellsig
* installing to library ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1’
* installing *source* package ‘cellsig’ ...
** using staged installation
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so':
  /stornext/System/data/apps/gcc/gcc-9.1.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so)
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: configuration failed for package ‘cellsig’
* removing ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/cellsig’
* restoring previous ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/cellsig’
```

**Comment by stemangiola** [comment]
Yes this is a problem I often run into. Can you please contact IT about this? For the moment do devtools::install(). Please read documentation and google tutorial Best wishes.Stefano  Stefano Mangiola | Postdoctoral fellowPapenfuss LaboratoryThe Walter Eliza Hall Institute of Medical Research+61 (0)466452544 From: jianwu1Sent: Tuesday, 13 July 2021 5:40 PMTo: stemangiola/cellsigCc: Stefano Mangiola; AuthorSubject: Re: [stemangiola/cellsig] 2- Design the algorithm such that it takes the input of a transcript abundance data frame(symbol, sample, count, cell_type) and a specified hierarchy. (Find the file in cellsig) output nodal signatures. (#10) reinstall cellsig (branch data-exploration)Hi Stefano,Can I ask how to reinstall cellsig?I tried this command:R CMD INSTALL --preclean --no-multiarch --with-keep.source ../cellsigBut the error says version `GLIBCXX_3.4.29' not found (I searched for the error online but could find anything ***@***.*** cellsig]$ R CMD INSTALL --preclean --no-multiarch --with-keep.source ../cellsig * installing to library ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1’ * installing *source* package ‘cellsig’ ... ** using staged installation Error in dyn.load(file, DLLpath = DLLpath, ..) :    unable to load shared object '/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so':   /stornext/System/data/apps/gcc/gcc-9.1.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/libs/Rcpp.so) Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load Execution halted ERROR: configuration failed for package ‘cellsig’ * removing ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/cellsig’ * restoring previous ‘/stornext/Home/data/allstaff/w/wu.j/R/x86_64-pc-linux-gnu-library/4.1/cellsig’ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kamran-Khan96** [comment]
Resolved
