### ISSUE TITLE
Use posterior probabilities of estimated transcript abundance to rank the genes.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#11]
1. rank quantiles

**Comment by stemangiola** [comment]
Here is the visual comparison

![image](https://user-images.githubusercontent.com/7232890/126100246-56045d78-20dc-4a77-b32e-9c266b3c9457.png)

**Comment by jianwu1** [comment]
Hi Stefano,

1. When trying to calculate the mean of upper quantiles, I found that there are duplicate genes for certain cell types:
![image](https://user-images.githubusercontent.com/62498686/126629707-d17bfbd3-c32d-43fc-8b72-c1f541025722.png)
![image](https://user-images.githubusercontent.com/62498686/126627872-33c2ccd9-b626-4b0d-8cf3-889004003018.png)

2. There's another issue that some genes are present in one cell type but not in the other cell types of the same level and I'm planning to rectangularise the input quantile data by:
```
bayes %>% 
  # rectangularise data
  nest(data = -c(symbol, cell_type)) %>%
  add_count(symbol) %>%
  filter(n == max(n)) %>%
  unnest(data)
```

**Comment by stemangiola** [comment]
most likely you can select the first one, the ate pretty similar. I will investigate tomorrow.

**Comment by Kamran-Khan96** [comment]
Resolved
