### ISSUE TITLE
comment on commit ID and attach the benchmark plot for the pipeline

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#13]

**Comment by jianwu1** [comment]
optimisation method = curvature [ADD COMMIT ID]

![image](https://user-images.githubusercontent.com/62498686/123561944-d45d3a80-d7ee-11eb-913f-c5887005ac07.png)

**Comment by jianwu1** [comment]
Here is the plot generated from the output of random 7 streams and cibersortx. Deconvolution used only 10 mix matrices therefore only 10 points for each boxplot in C. [ADD COMMIT ID]

![image](https://user-images.githubusercontent.com/62498686/131482528-e888f224-d2ba-446c-818a-c4b447791ad7.png)

**Comment by stemangiola** [comment]
Thanks Jian,
- I rememebered the silhuette score giving better results than cibersortx
- what staops you from creating 100 mixtures?
- any luck with the Bayes contrasts?

I think we can approach the cell-type specific hierarchy and call it done for the selection method.

**Comment by jianwu1** [comment]
> Thanks Jian,
> 
> * I rememebered the silhuette score giving better results than cibersortx
> * what staops you from creating 100 mixtures?
> * any luck with the Bayes contrasts?
> 
> I think we can approach the cell-type specific hierarchy and call it done for the selection method.

I only randomly sampled  7 methods and 10 matrices for the ease of computation. I'll produce benchmark plots using 38 methods and 100 mixes on slurm.

If you think the styles and labels of plots in the pdf file I sent to your email are ok I'll run the script on slurm.

**Comment by stemangiola** [comment]
All good

**Comment by jianwu1** [comment]
before checking imputation threshold: [Commit ID: 0bd83c79dcbd765469c9ea4c540289ff7be50ab6  ]
![image](https://user-images.githubusercontent.com/62498686/132170812-9487bc88-bdb1-4305-8af1-1be243766b81.png)
![image](https://user-images.githubusercontent.com/62498686/132170900-a39a6151-fb55-4208-a9ce-37f36ba33211.png)
![image](https://user-images.githubusercontent.com/62498686/132170980-770e5a67-6c3c-4505-b287-7a3c86a46df1.png)

**Comment by jianwu1** [comment]
first benchmark comparing all 40 streams[commit_ID: 748bacf6a320fa46769e15b6932f000d04974101]:
Input count data were imputed within the preprocess function rather than pre-imputed. mix data for deconvolution also resulted from this count data. 
bayes data were preprocessed to make sure all cell types share the same set of transcripts and had duplicate genes removed.

![boxplot_silhouette](https://user-images.githubusercontent.com/62498686/132986061-233fb2dd-e005-43e9-b755-001f98f4d1d9.png)

![boxplot_deconvolution_by_method](https://user-images.githubusercontent.com/62498686/132986084-70e65626-952a-49b9-b7c0-2bb1b0e27f24.png)

![boxplot_deconvolution_by_cell_type](https://user-images.githubusercontent.com/62498686/132986091-5410f7bd-279a-4461-be47-355cf26aed29.png)

**Comment by Kamran-Khan96** [comment]
Resolved
