### ISSUE TITLE
Choose more PC for the silhouette score, and run the deconvolution benchmark and see if it improves, out methods compared to cibersortX

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#14]

**Comment by jianwu1** [comment]
Using tt_non_hierarchy (old data):
We could try 4 PCs and 10 PCs.
design matrix dimensions used for SVD:  954  x 16894
![image](https://user-images.githubusercontent.com/62498686/132115920-a9a7c9e7-8ae2-4c16-acae-5f164b56dbb5.png)
![image](https://user-images.githubusercontent.com/62498686/132115966-ccbbb268-d5f8-4f01-a2c8-3a1598b578fc.png)

**Comment by stemangiola** [comment]
> We could try 4 PCs and 10 PCs.

Agree

**Comment by jianwu1** [comment]
tSNE & UMAP

**Comment by jianwu1** [comment]
Using counts_imputed_non_hierarchy
try .dims =c(2, 4, 10)
![image](https://user-images.githubusercontent.com/62498686/134031355-df5e7f46-73bc-4ea6-b69a-83b28954ab37.png)

**Comment by jianwu1** [comment]
@stemangiola 

Hi Stefano, here's the plot, in response to your email: "could you please send me the UMAP plot of one of the signatures colouring by levels (level1, then level_2, then level_3, ...)"
only 2 dimensions are used. Cell types on the same level show clear separation.

![image](https://user-images.githubusercontent.com/62498686/134090125-75ff63b9-8581-4c8f-9eec-a733a226430a.png)

**Comment by stemangiola** [comment]
Thanks Jian,

so much separation, I was hoping a bit less. Here the silhouette score is going to get crazy. How many markers have you used, and for which method? Could you 

1) do the same for cibersort signature?
2) do the same with .dims argument = 10 (this is the number of PC used for calculating UMAP, now I think is using 20ish).

**Comment by jianwu1** [comment]
@stemangiola 
> How many markers have you used
signature size from hierarchical_mean_contrast_bayes_silhouette_curvature: 453;
signature size from cibersortx:  5172

**Comment by jianwu1** [comment]
@stemangiola 
> 1. do the same for cibersort signature?
better separation using 453 markers
![image](https://user-images.githubusercontent.com/62498686/134102348-ebd0339f-6663-4d09-9a0d-d9b7c58c97d6.png)

**Comment by jianwu1** [comment]
@stemangiola 
> 2\. do the same with .dims argument = 10 (this is the number of PC used for calculating UMAP, now I think is using 20ish).

I get this error when setting .dims=10 for UMAP, which is not present when method = "PCA:
```
Error: Problem with `mutate()` column `reduced_dimension`.
ℹ `reduced_dimension = map(...)`.
x Can't transform a data frame with duplicate names.
```

**Comment by jianwu1** [comment]
@stemangiola 

Hi Stefano,

I'm running 120 slurm jobs now for PCA using .dims = 2, 4, 10.
40 streams for each number of PCs.
I hope it's not too much.

**Comment by stemangiola** [comment]
don't worry you can launch 10K jobs, using -J 200 to limit the number of jobs launched at the same time.

**Comment by jianwu1** [comment]
benchmark signature using 2PCs and 10PCs (non_hierarchial signatures and cibersortx signatures are not 100% correct as all cell types were used rather than leaf cell types) [commit ID: a041e891212d855f24e9745ca56cb60f7d877dab]:
Silhouette score:
dim=2:
![boxplot_silhouette_dim2](https://user-images.githubusercontent.com/62498686/136361044-1ecb9bd8-d9ed-4310-8eea-7cbec0b09d80.png)
dim = 10:
![boxplot_silhouette_dim10](https://user-images.githubusercontent.com/62498686/136361102-b2840258-f4cf-417e-b1ed-afec56ce7034.png)

Deconvolution error rate:
dim = 2:
![boxplot_deconvolution_by_method_dim2](https://user-images.githubusercontent.com/62498686/136361210-625f6de6-d356-4a04-bc51-e8fe8a211d98.png)
dim = 10:
![boxplot_deconvolution_by_method_dim10](https://user-images.githubusercontent.com/62498686/136361264-ad29f34f-1f9d-4c3d-910b-a713858c92d9.png)

Deconvolution error rate with respect to cell types:
dim = 2:
![boxplot_deconvolution_by_cell_type_dim2](https://user-images.githubusercontent.com/62498686/136361378-2cde44a7-65e6-42b3-905e-1f5606374103.png)
dim = 10:
![boxplot_deconvolution_by_cell_type_dim10](https://user-images.githubusercontent.com/62498686/136361415-6ea8b1ca-e80f-4c19-822b-16dc9f3a8a6b.png)

**Comment by jianwu1** [comment]
@stemangiola 
Finalised benchmark: using new tree (treg as a sibling to t_helper) and the tip nodes for non_hierarchical and cibersortx:
PCA as reduction method;
Overall hierarchical_pairwise_contrast_bayes_silhouette_penalty gives cell signatures that result in the lowest median deconvolution error, it's ranked first in dim=4 and dim=10, ranked third in dim=2, and the same method with curvature optimisation was ranked first in dim2.
Dim4 captures the most variance in the data while not compromising distance-based silhouette metric too much.
Methods that ranked higher than cibersortx are all hierarchical methods. This shows the effectiveness of hierarchical approach, however, another reason could be because more signatures are selected in hierarchical approach: 1126 genes selected in hierarchical_pairwise_contrast_bayes_silhouette_penalty_4, yet 286 genes selected in non_hierarchical_pairwise_contrast_bayes_naive_penalty_4 (didn't run silhouette selection with non_hierarchical pairwise contrast methods due to the excessive computational load). 

In terms of cell_type specific deconvolution error, cibersortx performs the best stably.
In terms of silhouette score, cibersortx performs the worst and non_hierarchical methods perform the best especically with silhouette selection since it's the objective function.  

Deconvolution
Dim=2:
![image](https://user-images.githubusercontent.com/62498686/136638054-ac40d978-2798-49e5-915c-ab6d415a3f8c.png)
Dim=4:
![image](https://user-images.githubusercontent.com/62498686/136643309-5f1ebabf-b65c-4e81-9c09-9bd97a8300d0.png)
Dim=10:
![image](https://user-images.githubusercontent.com/62498686/136643331-89dc465f-8886-4ed9-8b85-d1fd5e45d7f8.png)


Silhouette:
Dim=2:
![image](https://user-images.githubusercontent.com/62498686/136636916-7bd6678d-e527-4095-9ca4-55c4b03c185a.png)
Dim=4:
![image](https://user-images.githubusercontent.com/62498686/136643367-c63490dc-ba41-4ea1-b28c-018eabb33c05.png)
Dim=10:
![image](https://user-images.githubusercontent.com/62498686/136643385-ad934447-8189-4749-a082-93d84a5de7df.png)


Cell type:
Dim=2:
![image](https://user-images.githubusercontent.com/62498686/136636978-9d3dae6c-1fdb-4d13-b39b-4f4221141297.png)
Dim=4:
![image](https://user-images.githubusercontent.com/62498686/136643412-960bb1ea-4cb1-4873-8d11-f43e20b68779.png)
Dim=10:
![image](https://user-images.githubusercontent.com/62498686/136643427-8aa69631-f60d-4151-83f5-93afd3c065bc.png)

**Comment by Kamran-Khan96** [comment]
Obsolete
