### ISSUE TITLE
generalise the ranking function with edgeR to arrange of a different column

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#15]
rank_function_edgeR(.., column_name){
 column_name = enquo(column_name)

... %>%
arrange(!!column_name)
}

rank_function_edgeR(..., `PValue`)
rank_function_edgeR(..., `LogFC`)

**Comment by stemangiola** [comment]
Instead of ranking on a different column (i.e. pvalue) let's change few things at the same time.

1) We detect differentially abundance transcript genes with the following robust implementation of edger

```r
counts_de = 
  counts_scaled %>%
  test_differential_abundance(
    ~..., 
    method="edger_robust_likelihood_ratio", 
    .contrasts = "..., 
    test_above_log2_fold_change = 1
  )
```
edger_robust_l rank by p-value only
2) rank base on pvalue

**Comment by Kamran-Khan96** [comment]
Resolved
