### ISSUE TITLE
For your user-oriented pipeline, produce an evaluation function that, given

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#19]
1) the original user-provided data set and
2) your signature output data set

provides a faceted boxplot, of the transcript abundance, for each gene and cell_type.

For example, if you have 4 genes and 4 cell types the plot should include 16 facets and four-gene elements on the x axis for each facet. You can fill by the cell type each marker is for, for 16 facets should be filled with four-colour, and each facet should only have one colour.

Additional feature:
Tell the user how confounded are cell-type pairs for deconvolution. For example, can you distinguish really between CD8 effector memory and central memory?
The method would be to build a mixture of one cells type (0-100%), deconvolute you measure the relative from pure 100%.

If you cannot distinguish between two cells types you would get 50%-50%.

**Comment by Kamran-Khan96** [comment]
Obsolete
