### ISSUE TITLE
compare PCA plots from all methods for macrophage, CD4, and CD8. 8 PCA plot for each cell

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#2]

**Comment by jianwu1** [comment]
CD4
![image](https://user-images.githubusercontent.com/62498686/118900643-cd701c00-b954-11eb-9482-8ef3ad6c61e9.png)
![image](https://user-images.githubusercontent.com/62498686/118900673-e2e54600-b954-11eb-958f-b13f257636cb.png)
![image](https://user-images.githubusercontent.com/62498686/118900713-f7c1d980-b954-11eb-8935-29344f33a2ba.png)
![image](https://user-images.githubusercontent.com/62498686/118900730-01e3d800-b955-11eb-937b-79cb09edafba.png)
![image](https://user-images.githubusercontent.com/62498686/118900944-7b7bc600-b955-11eb-9bfa-6261fd411482.png)
![image](https://user-images.githubusercontent.com/62498686/118900964-86365b00-b955-11eb-9115-733becf37842.png)
![image](https://user-images.githubusercontent.com/62498686/118900987-90f0f000-b955-11eb-8af7-a42ee9b09bda.png)
![image](https://user-images.githubusercontent.com/62498686/118901026-a82fdd80-b955-11eb-9fa2-7f1c873df940.png)
CD8
![image](https://user-images.githubusercontent.com/62498686/118901067-bbdb4400-b955-11eb-9624-9fe76de7733c.png)
![image](https://user-images.githubusercontent.com/62498686/118901091-cac1f680-b955-11eb-88da-462d7f26bb55.png)
![image](https://user-images.githubusercontent.com/62498686/118901103-d2819b00-b955-11eb-8d87-e6581790d3d8.png)
![image](https://user-images.githubusercontent.com/62498686/118901120-dd3c3000-b955-11eb-89b2-c39b32b9269e.png)
![image](https://user-images.githubusercontent.com/62498686/118901131-e62d0180-b955-11eb-9f61-f5334acfd33e.png)
![image](https://user-images.githubusercontent.com/62498686/118901169-f5ac4a80-b955-11eb-87cc-9a8f1cc12088.png)
![image](https://user-images.githubusercontent.com/62498686/118901199-0361d000-b956-11eb-8afc-0a8b6d75e359.png)
![image](https://user-images.githubusercontent.com/62498686/118901221-0ceb3800-b956-11eb-9a09-43b45ff4f47a.png)

**Comment by stemangiola** [comment]
Thanks Jian,

as I imagined in higher levels all the method perform equally quite poorly. I would like to observe, for one of the methods

- plot PC with top = Inf
- get the first 10 PCs and draw a heatmap with clustering (easy with tidyHeatmap)
- For method silhouette hierarchical see the PCs for only the node-specific markers. This to see how worst the PC plot gets when all markers are integrated
- See tSNE for one method (tidybulk), to see if we get more separation than 2 PC2

There are different routes:

- This means that there is really the opportunity for a cell-type-targeted feature selection
- 2 PC might not be enough. For this, there are two routes
- - Use tSNE instead (might be much slower)
- - Use more PCs and evaluate maybe k means clustering or hierarchical clustering. Do silhouette score works in more than 2 dimensions?

**Comment by jianwu1** [comment]
> * For method silhouette hierarchical see the PCs for only the node-specific markers. This to see how worst the PC plot gets when all markers are integrated

compare PCA from node-signature and overall-signature.

**Comment by jianwu1** [comment]
PCA from overall signature
Macrophage:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118927196-c3661180-b984-11eb-953d-d0ac8128cf48.png)
![image](https://user-images.githubusercontent.com/62498686/118927424-1e980400-b985-11eb-95c2-dab854213e68.png)
cibersortx
![image](https://user-images.githubusercontent.com/62498686/118927613-69198080-b985-11eb-9deb-1790a4d1f05f.png)
![image](https://user-images.githubusercontent.com/62498686/118927732-8fd7b700-b985-11eb-9f6c-d52866792ab9.png)
CD4:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118927881-c7defa00-b985-11eb-9c81-f96767a03db9.png)
![image](https://user-images.githubusercontent.com/62498686/118927936-ddecba80-b985-11eb-8a06-c4038f0109ac.png)
cibersortx
![image](https://user-images.githubusercontent.com/62498686/118928077-0f658600-b986-11eb-8701-935f09d666c7.png)
![image](https://user-images.githubusercontent.com/62498686/118928281-5b182f80-b986-11eb-9ac5-7c5aa36cbe65.png)
CD8:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118928544-b813e580-b986-11eb-859c-254587123237.png)
![image](https://user-images.githubusercontent.com/62498686/118928582-c5c96b00-b986-11eb-8fda-1d3f79ae68a2.png)
cibersortx
![image](https://user-images.githubusercontent.com/62498686/118928692-ed203800-b986-11eb-955c-5418d6588d43.png)
![image](https://user-images.githubusercontent.com/62498686/118928757-00cb9e80-b987-11eb-8c5e-10088a10c994.png)

**Comment by stemangiola** [comment]
Thanks. Please Jian, always "quote reply" so I am sure to what point you are replying, and which points remain. 

Heatmaps are done usually with features on the rows and elements on the columns. This will affect clustering. Please redraw heatmaps. As mentioned one method is enough, so you don't have so much work.

**Comment by jianwu1** [comment]
> * plot PC with top = Inf

PCA from overall signature
Macrophage:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118927196-c3661180-b984-11eb-953d-d0ac8128cf48.png)
CD4:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118927881-c7defa00-b985-11eb-9c81-f96767a03db9.png)
CD8:
mean_contrast.silhouette.non_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118928544-b813e580-b986-11eb-859c-254587123237.png)

**Comment by jianwu1** [comment]
> * See tSNE for one method (tidybulk), to see if we get more separation than 2 PC2
macrophage
mean_contrast.silhouette_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118931481-6c633b00-b98a-11eb-999c-cefc8729c59a.png)
CD4
mean_contrast.silhouette_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118931041-daf3c900-b989-11eb-95b4-b6d664caff7a.png)
CD8
mean_contrast.silhouette_hierarchy
![image](https://user-images.githubusercontent.com/62498686/118931730-a03e6080-b98a-11eb-90e9-97892b0c1b84.png)

**Comment by jianwu1** [comment]
> * get the first 10 PCs and draw a heatmap with clustering (easy with tidyHeatmap)
mean_contrast.silhouette.non_hierarchy
macrophage
![image](https://user-images.githubusercontent.com/62498686/118932686-a54fdf80-b98b-11eb-842f-5e443f59a3ac.png)
CD4
![image](https://user-images.githubusercontent.com/62498686/118932382-56a24580-b98b-11eb-89bd-82bbab1889d2.png)
CD8
![image](https://user-images.githubusercontent.com/62498686/118932800-cadce900-b98b-11eb-8d29-34badf6ed957.png)

**Comment by stemangiola** [comment]
>     * See tSNE for one method (tidybulk), to see if we get more separation than 2 PC2
>       macrophage
>       mean_contrast.silhouette_hierarchy

How many PCs did you use (parameter in the function I think) to calculate tSNE?

**Comment by stemangiola** [comment]
Are you using scale=FALSE I imagine for PCA?

**Comment by jianwu1** [comment]
> > ```
> > * See tSNE for one method (tidybulk), to see if we get more separation than 2 PC2
> >   macrophage
> >   mean_contrast.silhouette_hierarchy
> > ```
> 
> How many PCs did you use (parameter in the function I think) to calculate tSNE?

.dim = 2 for tSNE. The option says I can only choose 1, 2, or 3

**Comment by jianwu1** [comment]
> Are you using scale=FALSE I imagine for PCA?

No, I used scale=TRUE. Is it advised to scale features before doing PCA?
The previous problem disappeared after I removed genes with 0 standard deviation.

**Comment by stemangiola** [comment]
> No, I used scale=TRUE. Is it advised to scale features before doing PCA?

As discussed, for PCA scale=FALSE can help in our case, otherwise, all genes are given the same weight, even if they are almost non transcribed for Macrophages (for example)

Can you compare one plot with scale = T and F

[EDIT] you see variable feature selection (e.g. top 500 or top 10) eliminates all genes that are not informative for Macrophages but only add to the noise.  I think scale=FALSE and top selection should have the same result.

**Comment by stemangiola** [comment]
> .dim = 2 for tSNE. The option says I can only choose 1, 2, or 3

Those are the tSNE dimensions, but tSNE calculate the first 30 PC I think and use them. We should base tSNE on the first 10 PC probably. But is not crucial probably. 

PCA scale plays a bigger role probably.

**Comment by jianwu1** [comment]
> > No, I used scale=TRUE. Is it advised to scale features before doing PCA?
> 
> As discussed, for PCA scale=FALSE can help in our case, otherwise, all genes are given the same weight, even if they are almost non transcribed for Macrophages (for example)
> 
> Can you compare one plot with scale = T and F
> 
> [EDIT] you see variable feature selection (e.g. top 500 or top 10) eliminates all genes that are not informative for Macrophages but only add to the noise. I think scale=FALSE and top selection should have the same result.
CD4 PCA scale = FALSE
![image](https://user-images.githubusercontent.com/62498686/118935459-eb5a7280-b98e-11eb-8c40-f379bf67e00e.png)

CD4 PCA scale=TRUE
![image](https://user-images.githubusercontent.com/62498686/118935331-c534d280-b98e-11eb-883b-3e171386f058.png)

Yes, scale=FALSE gives better separation.

**Comment by stemangiola** [comment]
>     - For method silhouette hierarchical see the PCs for only the node-specific markers. This to see how worst the PC plot gets when all markers are integrated

The last thing is this. I want to confirm that the node-specific signature is good, while the overall is bad (for specific nodes).

**Comment by jianwu1** [comment]
> > ```
> > - For method silhouette hierarchical see the PCs for only the node-specific markers. This to see how worst the PC plot gets when all markers are integrated
> > ```
> 
> The last thing is this. I want to confirm that the node-specific signature is good, while the overall is bad (for specific nodes).
mean_contrast.silhouette.hierarchy
macrophage
![image](https://user-images.githubusercontent.com/62498686/118943252-ca961b00-b996-11eb-8ed4-27e1adcbfe81.png)
CD4
![image](https://user-images.githubusercontent.com/62498686/118943400-ec8f9d80-b996-11eb-8443-6d408a5a1fea.png)
CD8
![image](https://user-images.githubusercontent.com/62498686/118943480-029d5e00-b997-11eb-87d7-4530d2255a6b.png)

pairwise.silhouette.hierarchy
macrophage
![image](https://user-images.githubusercontent.com/62498686/118942090-c0275180-b995-11eb-903d-6dded338d4d1.png)
CD4
![image](https://user-images.githubusercontent.com/62498686/118940962-97528c80-b994-11eb-942a-aa4201eb89d3.png)
CD8
![image](https://user-images.githubusercontent.com/62498686/118941332-f2847f00-b994-11eb-9395-44e554caea8b.png)

Hierarchical signature benefits resolving cell types under a certain node.

**Comment by jianwu1** [comment]
I think the next step is to include more principal components to see if a better resolution can be achieved.

**Comment by stemangiola** [comment]
How many markers for mean hierarchical CD4 and  mean hierarchical overall?

We need to decrease the markers for lower levels  until we se separation for CD4. And then check if we see separation for lower levels.

Tomorrow we can have a short chat if you did not understand.

**Comment by jianwu1** [comment]
> How many markers for mean hierarchical CD4 and mean hierarchical overall?
> 
> We need to decrease the markers for lower levels until we se separation for CD4. And then check if we see separation for lower levels.
> 
> Tomorrow we can have a short chat if you did not understand.

284 markers from mean_contrast.silhouette.hierarchy overall are used to resolve CD4 (t_CD4_memory_central, t_CD4_memory_effector, t_reg, t_helper_h1, t_helper_h2, t_helper_h17);

44 markers combined from the nodes below of mean_contrast.silhouette.hierarchy are used to resolve CD4: 
`c("t_CD4_memory_central", "t_CD4_memory_effector", "t_reg", "t_helper_h1", "t_helper_h2", "t_helper_h17")`

![image](https://user-images.githubusercontent.com/62498686/119060886-76cb1680-ba16-11eb-86d9-3c5f8979c9df.png)

**Comment by stemangiola** [comment]
> 284 markers from mean_contrast.silhouette.hierarchy overall are used to resolve CD4 (t_CD4_memory_central, t_CD4_memory_effector, t_reg, t_helper_h1, t_helper_h2, t_helper_h17);
> 
> 44 markers combined from the nodes below of mean_contrast.silhouette.hierarchy are used to resolve CD4:

I would like to observe four things

- if we eliminate markers for levels 1 and 2 and keep markers for levels 3 and 4, how the separation looks?
- How many markers do we have for each level?
- if 44 markers resolve CD4s and 284 compromise resolution, what if we subsample the remaining markers (NON-CD4s, eliminate 10%, 20%, 30%) until we see separation again of CD4s.
- what if we do this subsampling of foreign markers for lower levels only (1 and 2) 
- We see that PCA and tSNE are sensitive to markers noise accumulation, so if we do deconvolution of CD4s phenotypes for CD4 markers or overall signature, do we see a decrease of the CD4s deconvolution accuracy?

This will tell us what is the effect of lower-level markers on higher level nodes.

**Comment by jianwu1** [comment]
> * How many markers do we have for each level?

![image](https://user-images.githubusercontent.com/62498686/119071738-b6e9c380-ba2d-11eb-9d0a-f77e92f7843c.png)

**Comment by jianwu1** [comment]
> * if we eliminate markers for levels 1 and 2 and keep markers for levels 3 and 4, how the separation looks?

![image](https://user-images.githubusercontent.com/62498686/119092885-528d2b00-ba52-11eb-8d8e-f2330b32ffe7.png)
There is little improvement as 141 markers excluding markers from level_1 and level_2 still contain a lot more genes that lead to noise than the 44 genes that specifically resolve CD4 subtypes.

**Comment by jianwu1** [comment]
> * if 44 markers resolve CD4s and 284 compromise resolution, what if we subsample the remaining markers (NON-CD4s, eliminate 10%, 20%, 30%) until we see separation again of CD4s.
There are 240 non_CD4 markers out of the 284 overall signature.
![image](https://user-images.githubusercontent.com/62498686/119096804-625b3e00-ba57-11eb-87fd-fe35633792b4.png)
![image](https://user-images.githubusercontent.com/62498686/119096889-7dc64900-ba57-11eb-984c-9168d57b3920.png)
![image](https://user-images.githubusercontent.com/62498686/119097021-9fbfcb80-ba57-11eb-851d-3afefd815725.png)

**Comment by stemangiola** [comment]
Interesting. We know the issue now (whether is solvable I don't know). I think is time to see whether deconvolution of CD4s decrease in accuracy as much as the PCA, or the deconvolution does not care so much about the noise.

Otherwise, we take the risk of working like crazy to fix PCA and maybe does not matter at all.

**Comment by jianwu1** [comment]
> * what if we do this subsampling of foreign markers for lower levels only (1 and 2)

There are 143 markers from all nodes of L1 and L2 combined.
![image](https://user-images.githubusercontent.com/62498686/119098864-a8190600-ba59-11eb-9573-848633cf7480.png)
![image](https://user-images.githubusercontent.com/62498686/119098951-c1ba4d80-ba59-11eb-92bf-440d9f9ec661.png)
![image](https://user-images.githubusercontent.com/62498686/119099089-e3b3d000-ba59-11eb-97cc-bc517b4700ed.png)
The resolution is better because the noise level is lower.

**Comment by stemangiola** [comment]
> The resolution is better because the noise level is lower.

Wow OK so are the levels 3, 4, 5 that cause a mess. Is it possible that there is a specific level/node that is causing the mess?

**Comment by stemangiola** [comment]
> > * How many markers do we have for each level?
> 
> ![image](https://user-images.githubusercontent.com/62498686/119071738-b6e9c380-ba2d-11eb-9d0a-f77e92f7843c.png)

- Can I please see the optimisation curve for level 1 that led to 120 genes?
- Can I please see the optimisation curve for node CD4 that led to ... genes?

**Comment by stemangiola** [comment]
lot PCs for CD4s +
-  lv1, or
- lv2, or
- lv3 ..

**Comment by jianwu1** [comment]
> lot PCs for CD4s +
> 
> * lv1, or
> * lv2, or
> * lv3 ..

 PCA from pure CD4 signature for contrast
![image](https://user-images.githubusercontent.com/62498686/119759016-d16ae380-beea-11eb-9383-8ca419790e57.png)

![image](https://user-images.githubusercontent.com/62498686/119756981-a337d480-bee7-11eb-96e6-51c28f2228e5.png)

![image](https://user-images.githubusercontent.com/62498686/119756508-fd846580-bee6-11eb-9ba0-9178e5f11498.png)
![image](https://user-images.githubusercontent.com/62498686/119756614-1bea6100-bee7-11eb-85bb-a79a996b2569.png)
![image](https://user-images.githubusercontent.com/62498686/119756694-36243f00-bee7-11eb-9838-ff991ff75e90.png)
![image](https://user-images.githubusercontent.com/62498686/119756786-52c07700-bee7-11eb-9c4f-dda3e0a3bf3b.png)
![image](https://user-images.githubusercontent.com/62498686/119756846-69ff6480-bee7-11eb-947e-58f08c5a7409.png)

same number of noise (21) from each level
![image](https://user-images.githubusercontent.com/62498686/119758678-412c9e80-beea-11eb-80d2-dabb129c1280.png)

![image](https://user-images.githubusercontent.com/62498686/119758454-e98e3300-bee9-11eb-8e33-e0c39a962756.png)
![image](https://user-images.githubusercontent.com/62498686/119758492-fca10300-bee9-11eb-9fce-25e8d44e78c2.png)
![image](https://user-images.githubusercontent.com/62498686/119758568-117d9680-beea-11eb-80ae-ff1caa8ca715.png)
![image](https://user-images.githubusercontent.com/62498686/119758607-23f7d000-beea-11eb-8369-fd110989f82d.png)

**Comment by Kamran-Khan96** [comment]
Resolved
