### ISSUE TITLE
show that ratiop_imputed_samples for the bayes and non_bayes datasets is the same for c(cell_type, symbol) pairs.

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#21]
For benchmark do not filter imputation ratio
for user pipeline do filter for imputation ratio

**Comment by jianwu1** [comment]
### level_1
![image](https://user-images.githubusercontent.com/62498686/133770655-511a5450-e0fe-4191-809b-97df162dd7a0.png)
### level_2
![image](https://user-images.githubusercontent.com/62498686/133770897-52aa9bee-a344-4dcb-a62d-7e37623ac9dd.png)
### level_3
![image](https://user-images.githubusercontent.com/62498686/133771093-7d725b2b-bddd-407a-8afe-4e7e6f362dbc.png)
### level_4
![image](https://user-images.githubusercontent.com/62498686/133771226-b3ebdd33-0c6e-441c-bb22-8e18bb089256.png)
### level_5
![image](https://user-images.githubusercontent.com/62498686/133771394-5451b0be-0f93-4c1f-a7c8-886c262d401f.png)

### example dataframe for plotting:
![image](https://user-images.githubusercontent.com/62498686/133771581-3344f9d4-0a28-4181-a559-82fd01fd4b44.png)

**Comment by Kamran-Khan96** [comment]
Resolved
