### ISSUE TITLE
Gene expression visualisation in leaf cell types at each level.

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#27]

**Comment by jianwu1** [comment]
Interface:
![image](https://user-images.githubusercontent.com/62498686/136410919-23dff1e6-c7d1-4218-b551-e608d673d22c.png)
level_1:
![image](https://user-images.githubusercontent.com/62498686/136411023-48589b86-728f-4385-a510-0cb42e7d7699.png)
level_2:
![image](https://user-images.githubusercontent.com/62498686/136411118-e4ab9b5e-40c4-44c1-b134-9949415da381.png)
level_3:
![image](https://user-images.githubusercontent.com/62498686/136411214-1da7fd4c-f254-4294-bedd-f6d63435891b.png)
level_4:
![image](https://user-images.githubusercontent.com/62498686/136411319-15e363ad-6498-43ae-9761-f55c6c046653.png)
level_5:
![image](https://user-images.githubusercontent.com/62498686/136411409-061d5925-a996-4436-8095-0cf5aae66b57.png)

**Comment by jianwu1** [comment]
Interface:
![image](https://user-images.githubusercontent.com/62498686/137607622-1ac868fe-582d-4d1e-8940-cdd93f5fb4bf.png)
level1:
![image](https://user-images.githubusercontent.com/62498686/137607649-2b19d4db-ffb7-4640-a069-b8b40354922b.png)
level2:
![image](https://user-images.githubusercontent.com/62498686/137607670-ab8dc757-f8fa-4d50-a407-8b32cc4d2afb.png)
level3:
![image](https://user-images.githubusercontent.com/62498686/137607680-283e26ab-9e66-4a39-ac4e-e716729078f4.png)
level4:
![image](https://user-images.githubusercontent.com/62498686/137607692-cbfdd114-8899-4499-be69-23f6c513d2ff.png)
level5:
![image](https://user-images.githubusercontent.com/62498686/137607710-882634e4-4b82-4fd5-8333-068c76d8474c.png)

**Comment by stemangiola** [comment]
This interface seems pretty clean 

https://crukci.shinyapps.io/brca1tumourigenesis/

**Comment by jianwu1** [comment]
> This interface seems pretty clean

Hi @stemangiola,

Thanks for the template!!

**Comment by stemangiola** [comment]
> > This interface seems pretty clean
> 
> Hi @stemangiola,
> 
> Thanks for the template!!

If a public repository exists of this interface on github would be amazing, as we just would need to adapt. Otherwise, maybe just take as inspiration, and start with omitting levels or signatures, and replicate such interface. We can then build upon it.

**Comment by Kamran-Khan96** [comment]
Resolved
