### ISSUE TITLE
interactive visualisation of leaf cell type separation at each level and their signatures

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#28]

**Comment by jianwu1** [comment]
interface:
![image](https://user-images.githubusercontent.com/62498686/136563680-b7648c83-99b1-448c-8978-3371a9e860d7.png)

level_1:
![image](https://user-images.githubusercontent.com/62498686/136563885-38244953-2f62-42dc-aaaf-9c585e252a4c.png)

level_2:
![image](https://user-images.githubusercontent.com/62498686/136564140-e807c393-14f7-4a9e-a8b4-9bd774ffbb60.png)

level_3:
![image](https://user-images.githubusercontent.com/62498686/136564633-9e14a922-8571-4f11-b80f-d17f79937b42.png)

level_4:
![image](https://user-images.githubusercontent.com/62498686/136564837-4aaa2ef3-8ffd-40ad-820e-d22ec1463d01.png)

level_5:
![image](https://user-images.githubusercontent.com/62498686/136565394-e6103833-77e9-4c7c-a672-73a226faaf7d.png)

non_hierarchical:
![image](https://user-images.githubusercontent.com/62498686/136582161-b3033add-3d69-46fa-b84a-64a1c510df85.png)

**Comment by Kamran-Khan96** [comment]
Obsolete
