### ISSUE TITLE
Thesis Figures

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#29]

**Comment by jianwu1** [comment]
Figure-1
![image](https://user-images.githubusercontent.com/62498686/137733989-c869814b-d62a-401d-9960-ef95c7fd3ea9.png)

Figure-2
hierarchical_pairwise_contrast_bayes_silhouette_penalty_PCA_dim4 (plotted with tSNE):
![image](https://user-images.githubusercontent.com/62498686/137258516-e1d37fb2-5796-4887-9d46-e39f5fe1c198.png)
hierarchical_pairwise_contrast_bayes_silhouette_penalty_tSNE_dim2:
![image](https://user-images.githubusercontent.com/62498686/137605470-49003bf5-06db-45ca-b088-8cd446cfb19f.png)

Figure-3
![image](https://user-images.githubusercontent.com/62498686/137493948-bba64253-81cd-4e91-b345-c7ad1e4f0569.png)
![image](https://user-images.githubusercontent.com/62498686/137726930-87683ca1-2a28-4b01-80e7-80b67d8a2db1.png)

**Comment by jianwu1** [comment]
bandwidth=0.01
![image](https://user-images.githubusercontent.com/62498686/137836556-151367bc-8155-42c4-80eb-a750597ba9e5.png)
bandwidth=0.05
![image](https://user-images.githubusercontent.com/62498686/137836813-df360493-d4f9-4a3e-9509-8443317fe22f.png)
bandwith = 0.1
![image](https://user-images.githubusercontent.com/62498686/137837196-5ba80c1f-e182-4731-a91e-02b41333f82d.png)

**Comment by jianwu1** [comment]
![image](https://user-images.githubusercontent.com/62498686/137838138-f5cc3c49-f5ff-4bb2-9d44-57c54320f0df.png)

![image](https://user-images.githubusercontent.com/62498686/137838298-38764ec2-10d4-4be0-af92-fc2f24c210f8.png)

**Comment by jianwu1** [comment]
![image](https://user-images.githubusercontent.com/62498686/137849921-18d5c116-2a7b-41bb-aa35-54da3ef9655e.png)

![image](https://user-images.githubusercontent.com/62498686/137850000-a7856270-2bb3-4e06-960b-ce2db1ca17b1.png)

**Comment by stemangiola** [comment]
Much better

**Comment by Kamran-Khan96** [comment]
Resolved
