### ISSUE TITLE
Produce bar plot based on deconvolution accuracy rather than siluette score

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#3]

**Comment by stemangiola** [comment]
Hello @jianwu1,

the next step is to produce the barplot according to the accuracy of deconvolution

1) update the repository (pull), and rebuild the package
2) Download the imputed counts https://wehieduau-my.sharepoint.com/:u:/g/personal/mangiola_s_wehi_edu_au/ESbIOgjNL_tKsOTFOisCOCoBx5MiffWS-7wkoVjLBBhK0w?e=6EsAL7 (do not commit this file is too big) and place them into dev/
3) execute this code to generate S mixtures and test them


```r

load("dev/counts_imputed.rda")


mix_base = 
  counts_imputed %>%
  
  # keep genes present in all
  filter(count_scaled %>% is.na %>% `!`) %>%
  nest(data = -c(cell_type, symbol)) %>%
  add_count(symbol) %>%
  filter(n == max(n)) %>%
  unnest(data) %>% 
  select(-n)

S = 1

proportions = 
  gtools::rdirichlet(S, rep(1, length(unique(mix_base$cell_type)))) %>%
  as.data.frame() %>%
  setNames(unique(mix_base$cell_type))

mix = generate_mixture_from_proportion_matrix(mix_base, proportions) 


tidybulk::deconvolve_cellularity(
  mix,
  replicate, symbol, count_mix,
  #reference = ...,
  method = "llsr", 
  prefix = "llrs_", 
  action = "get"
  ) %>%
  pivot_longer(cols=starts_with("llrs_"), names_prefix ="llrs_", names_to="cell_type", values_to="estimated_proportion") %>%
  left_join(
    mix %>% 
      unnest(data_samples) %>% 
      distinct(replicate, cell_type, proportion)
  )
```

4) in reference = put your reference signature from the 8 algorithms

**Comment by jianwu1** [comment]
Hi Stefano,

Can I ask from which package this generate_mixture_from_proportion_matrix() function comes from? It's not one of the tidybulk unitilities:
 `mix = generate_mixture_from_proportion_matrix(mix_base, proportions) `

**Comment by stemangiola** [comment]
Cellsig. Look at the scripts in the R directory. I'm pretty sure I have
update the github

**Comment by jianwu1** [comment]
Methods comparison by silhouette score:
![image](https://user-images.githubusercontent.com/62498686/120622972-a3fdd700-c4a2-11eb-9bd2-4d9852d7ebf3.png)
Methods comparison by deconvolution mean squared error (MSE):
![image](https://user-images.githubusercontent.com/62498686/120623117-c42d9600-c4a2-11eb-9115-55624f5331d5.png)

**Comment by stemangiola** [comment]
That's great. We see we can do already better than Cibersort even for deconvolution. 



> Methods comparison by silhouette score:

Could you please produce a box plot instead where each data point is a node/method pair? Does not matter if the method is hierarchical or not. You can
-  nest based on the parent node
- calculate siluette
- unnest and plot



> Methods comparison by deconvolution mean squared error (MSE):

Similarly, could you please produce a box plot instead where each data point is a cell-type/method pair?

**Comment by jianwu1** [comment]
Hi Stefano,

I haven't updated on your request because there is a very bad news. I saw that the number of signature sizes selected somehow differ from my previous results, and I think this is because before when computing silhouette score the parameters for reduce_dimensions() were set as default using: top=500 and scale = TRUE.  After changing the default to top=Inf and scale = FALSE, the optimal signature size has become bigger for each node and the results are not as good as before in terms of deconvolution. 

Before  when  top=500 and scale = TRUE:
![image](https://user-images.githubusercontent.com/62498686/120889828-5c15b600-c642-11eb-926d-550dc31ed962.png)
Now when top=Inf and scale = FALSE:
![image](https://user-images.githubusercontent.com/62498686/120889866-88c9cd80-c642-11eb-9c0e-575e2309c91d.png)


I'll verify this before messaging you further.

Kind regards,

Jian

**Comment by stemangiola** [comment]
Hello Jian, I have updated the `generate_mixture_from_proportion_matrix` function now takes 8 times less.

Please if you can in the future look into these things as well. You will be much more independent then.

Results are good, I would like to see 100 samples (with new function) and boxplots (each data point is a cell type) rather than bar plots

**Comment by jianwu1** [comment]
> Hello Jian, I have updated the `generate_mixture_from_proportion_matrix` function now takes 8 times less.
> 
> Please if you can in the future look into these things as well. You will be much more independent then.
> 
> Results are good, I would like to see 100 samples (with new function) and boxplots (each data point is a cell type) rather than bar plots

Hi Stefano, 
The first plot is boxplot using cell type as each data point, however, I'm not sure if this is what you want:
![image](https://user-images.githubusercontent.com/62498686/123529376-e1b4ef00-d732-11eb-8891-249cc02cebbe.png)
If you want to use boxplot to compare MSE for different methods and see if one is significantly better than the other, I think the plot below might be more appropriate using the MSE for each mixture matrix as data points (100 points for each method):
![image](https://user-images.githubusercontent.com/62498686/123529618-6ef94300-d735-11eb-8557-c064d8e7a7ce.png)
The difference may not be significant but the IQR shows that the hierarchy + silhouette methods have lower variability about the median of MSE than cibersortx.

**Comment by stemangiola** [comment]
Great. Please color by cell type not by method.

Please complete pipeline so to give me the signature for the tree I gave
you.

Then it would be good to develop a cell-type s p ecific signature and show
that for that specific Cell Type we can beat  Cibersort by a lot.

**Comment by jianwu1** [comment]
> Great. Please color by cell type not by method. Please complete pipeline so to give me the signature for the tree I gave you. Then it would be good to develop a cell-type s p ecific signature and show that for that specific Cell Type we can beat Cibersort by a lot.

![image](https://user-images.githubusercontent.com/62498686/123530602-a8cf4700-d73f-11eb-9697-32386d0d7275.png)
![image](https://user-images.githubusercontent.com/62498686/123530649-3b6fe600-d740-11eb-9df6-206183680ae3.png)

**Comment by stemangiola** [comment]
What I meant was

![image](https://user-images.githubusercontent.com/7232890/123530700-bcc77880-d740-11eb-8054-0cc9d2eaad51.png)

In this figure each data point should be a summary of a cell type for all the tests. Each boxplot should have 34 (or whatever) cell types.

**Comment by jianwu1** [comment]
> In this figure each data point should be a summary of a cell type for all the tests. Each boxplot should have 34 (or whatever) cell types.

![image](https://user-images.githubusercontent.com/62498686/123534572-77677300-d761-11eb-9fd4-333bd179b4dd.png)

**Comment by stemangiola** [comment]
Thanks can you send me this exact figure with the points colored by cell-type?

**Comment by jianwu1** [comment]
> Thanks can you send me this exact figure with the points colored by cell-type?

![image](https://user-images.githubusercontent.com/62498686/123561944-d45d3a80-d7ee-11eb-913f-c5887005ac07.png)

**Comment by Kamran-Khan96** [comment]
Resolved
