### ISSUE TITLE
all *_join should have the by= argument

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#30]
Hello @jianwu1 , 

please when you have time **all**  *_join should have the by= argument. I am spending many hours with @ZijieGA and this aspect is causing the code to be fragile, and not robust, causing many errors very hard to debug.

**Comment by jianwu1** [comment]
> Hello @jianwu1 ,
> 
> please when you have time **all** *_join should have the by= argument. I am spending many hours with @ZijieGA and this aspect is causing the code to be fragile, and not robust, causing many errors very hard to debug.

Hi @stemangiola ,

Sorry Stefano! Do you mind giving me a screenshot of where you found the bug? I did a text search through my function file and found only one spot in deconvolution_evaluation that does not have a specification of "by=".

Could it be a version issue? I have checked that the function_jian.R file stefano>cellsig>jian branch>dev/jian_R_files/function_jian.R to be the same as the file I pushed.

**Comment by stemangiola** [comment]
> Sorry Stefano! Do you mind giving me a screenshot of where you found the bug? I did a text search through my function file and found only one spot in deconvolution_evaluation that does not have a specification of "by=".

Weel then that might be it. I don't have the screenshot. We are using cibersort as we could not complete your scripts, keep giving errors, and Zijie needs presentation by tomorrow.

We should meet when you have some air, and see how you can test your scripts for Zijie (they will need to be robust for the community).

By the way, now I understand much more the fragility of CibersortX and how we can easily show the great things about your method. (of course beside the resource you provide which is already impactful as it is).

**Comment by Kamran-Khan96** [comment]
Obsolete
