### ISSUE TITLE
Test tidybulk again as_SummarizedExperiment

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#31]

**Comment by stemangiola** [comment]
@jianwu1 when you have time, could you please test again as_SummarizedExperiment straight from tibble that was failing before.

I added a fix at tidybulk@tibble_to_SE

**Comment by jianwu1** [comment]
> @jianwu1 when you have time, could you please test again as_SummarizedExperiment straight from tibble that was failing before.

@stemangiola 
Hi Stefano,

Yes, as_SummarizedExperiment now works without the need of having a tidybulk object as an input. Thanks!
