### ISSUE TITLE
publish the app on a server

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#32]

**Comment by jianwu1** [comment]
@stemangiola 
Hi Stefano,

The app is now hosted on shinyapp.ios:

[https://jianwu1.shinyapps.io/shiny_pub/]( https://jianwu1.shinyapps.io/shiny_pub/)

Using integer counts may exhibit large expression variations across samples of the same cell type.

**Comment by Kamran-Khan96** [comment]
Resolved
