### ISSUE TITLE
Try sparse matrix from Matrix of delayedArray for storing expression matrix for SummarizedExpriment object

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#33]

**Comment by stemangiola** [comment]
Hello @jianwu1 ,

the app looks great but takes long time to load. Can you do experiment to replace the standard matrix in the SummarizedExperiment object with
- sparse matrix from Matrix:: , or
- DelayedArray

They are legal expression containers rather than the matrix for the assay field in a SummarizedExperiment object, read below
https://bioconductor.org/packages/devel/bioc/manuals/SummarizedExperiment/man/SummarizedExperiment.pdf

Probably is gives good performances sparse matrix is the easiest to try, as it takes one line of code.

**Comment by jianwu1** [comment]
> Can you do experiment to replace the standard matrix in the SummarizedExperiment object with

@stemangiola 
Hi Stefano,

OK I'll attempt with sparse matrix. Thanks!

**Comment by Kamran-Khan96** [comment]
Resolved
