### ISSUE TITLE
Build figure 1 and draft figure 3.

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#34]

**Comment by jianwu1** [comment]
@stemangiola 
Figure1a:
For leaf cell types  sample number is not affected by hierarchical or non-hierarchical methods.
![image](https://user-images.githubusercontent.com/62498686/146723199-d7ff2851-fbc6-4ede-ba07-394714234229.png)
Figure1b:
![image](https://user-images.githubusercontent.com/62498686/146725814-c2babc12-05af-4532-a2de-37ef6e7a190f.png)
Figure1c:
library size:

**Comment by Kamran-Khan96** [comment]
Obsolete
