### ISSUE TITLE
Evaluation plots of the effect of Bayesian estimated gene expression distribution vs empirical gene expression from samples of various sizes

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#36]

**Comment by stemangiola** [comment]
What do you mean, installing the package will update the model. The new model takes into account datasets of origin. Can you please reformulate?

**Comment by jianwu1** [comment]
@stemangiola 
Hi Stefano,
Here is an evaluation of the gene expression distribution estimated from the model.
![IQR_bayes_vs_empirical](https://user-images.githubusercontent.com/62498686/156727363-dbb44473-8b0f-4154-a2d1-4f1f4dd12b88.PNG)
I selected the most variable gene (by IQR.bayes) from each of the cell type and looked at their empirical expression across samples. The black bars indicate the median of the estimated gene expression from bayesian model. So for example, SNORD22 expression is estimated to have a higher variation in t_helper cells by Bayesian model than empirical data(imputed). The black bar for SNORD22 (median of SNORD22 expression in t_helper cells) is much higher than the empirical expression of SNORD22 in samples we have.
![empirical_counts_of_genes_highly_variable_in_bayes](https://user-images.githubusercontent.com/62498686/156727418-54611151-4e0b-4e0f-aca4-5d57b50f4aae.PNG)

![mean_bayes_vs_empirical](https://user-images.githubusercontent.com/62498686/156727430-9b0a02df-7e0a-4aaf-a84d-a5cde299c2ef.PNG)
I selected the gene with mean expression of the highest deviation(mean.bayes against means.empirical) from each of the cell type and looked at their empirical expression across samples. The black bars indicate the median of the estimated gene expression from bayesian model.
![empirical_counts_of_genes_with_higher_mean_in_bayes](https://user-images.githubusercontent.com/62498686/156727440-45451042-c581-4dc9-81f3-79f0c9fc061c.PNG)

I think the plots show that Bayesian estimated gene expression preserves the variability of imputed genes. However, for unimputed genes, such as in t_CD8_naive, the bayesian estimated gene expression variation is much higher than the empirical expression.

**Comment by jianwu1** [comment]
for comparision, the plot using the Bayes model before:
![figure4](https://user-images.githubusercontent.com/62498686/156731107-9b0776b4-a85a-402a-80e7-71ac47d44424.png)

**Comment by stemangiola** [comment]
Hello Jian,

this can make sense, in case we have just one dataset, and extreme consistency within that dataset. We would fool us that that world would be so consistent, while it is just one laboratory has output a dataset with no variation. Can you

1) color by dataset, and add feature in the x axis
2) tell me if this datapoint are imputed somehow? For example T helper h1 I see a lot of points > 0 but with sd ~ 0. Very peculiar for experimental data.

**Comment by jianwu1** [comment]
@stemangiola 


> this can make sense, in case we have just one dataset, and extreme consistency within that dataset.
I see. You are right Stefano, the CD8_naive cells only have 4 datasets in the collection, which is reflected by its few data points in the boxplot. The small dataset should be the cause of artificially small empirical gene expression variation.




> 1. color by dataset, and add feature in the x axis
![color_by_dataset](https://user-images.githubusercontent.com/62498686/156817533-a613f646-9aab-43c6-9116-4c990d989832.png)



> 2\. T helper h1 I see a lot of points > 0 but with sd ~ 0. Very peculiar for experimental data.
Hi Stefano, you are right, most of the invariant gene expressions are imputed.
![invariant_imputed_genes](https://user-images.githubusercontent.com/62498686/156817776-ae766099-2977-40b0-9d26-775480416a9d.png)

I just have another question about imputation, which is actually the question brought to me in my final thesis talk. Someone asked if the imputation by cell type would distort the biological expression of genes in cell types and I didn't comprehend it fully back then. When we have a few samples of the same cell type, the transcriptomic differences between samples are technical missing values and ought to be imputed. However, when we use the gene expression of child cell types to impute its expression in the parent cell types, even level by level, wouldn't that confound the biological differences?

**Comment by stemangiola** [comment]
To do:

1) select imputed different between beayes and non-bayes and draw boxplots, coloured by dataset
2) select imputed excluding 0 counts and do the same
3) select unimputed and do the same
4) select genes imputed with the mean difference and do the same
5) select genes unim[uted with the mean difference and do the same
6) draw a boxplot for genes where the bayes mean = 0 and arithmetic mean > 0

**Comment by jianwu1** [comment]
@stemangiola 
> 1. select imputed different between bayes and non-bayes and draw boxplots, coloured by dataset
![IQR_bayes_vs_empirical](https://user-images.githubusercontent.com/62498686/156885030-9264281f-3e65-49dd-8d99-b1d6ee2711d2.PNG)
<img width="1440" alt="highly_variable_imputed_genes" src="https://user-images.githubusercontent.com/62498686/156889400-0b79c270-6792-4d2e-b96a-556646a34911.PNG">




> 2\. select imputed excluding 0 counts and do the same
![highly_variable_imputed_non_zero](https://user-images.githubusercontent.com/62498686/156885092-728b80af-eb1d-4c1b-a6a8-56f0e6465a88.png)

<img width="1440" alt="highly_variable_non_zero_imputed_genes" src="https://user-images.githubusercontent.com/62498686/156889662-1dfb1c52-cd5c-4bdf-9110-e4c344f46b7d.PNG">


> 3\. select unimputed and do the same
![highly_variable_unimputed_genes](https://user-images.githubusercontent.com/62498686/156885111-954320d7-efa4-4c93-96f1-34c2cbf4b356.png)

<img width="1440" alt="highly_variable_unimputed_genes(1)" src="https://user-images.githubusercontent.com/62498686/156890070-e870acff-0915-4b3a-862d-5b02cb2c83f5.PNG">



> 4\. select genes imputed with the mean difference and do the same
<img width="1440" alt="high_mean_difference_imputed" src="https://user-images.githubusercontent.com/62498686/156892043-1026490a-3ab9-4032-bd5f-262881d44244.PNG">


<img width="1440" alt="imputed_genes_with_highest_mean_difference" src="https://user-images.githubusercontent.com/62498686/156892775-ae9d7a8d-2e02-489d-ac0f-c0d7a4eb2241.PNG">





> 5\. select genes unim[uted with the mean difference and do the same
<img width="1440" alt="high_mean_difference_unimputed" src="https://user-images.githubusercontent.com/62498686/156892047-b998c95f-ab9a-4655-8795-7e873cb0aab7.PNG">


<img width="1440" alt="unimputed_genes_highest_diference_in_mean" src="https://user-images.githubusercontent.com/62498686/156892807-99252b94-0a79-45eb-9c0d-406cbef381de.PNG">



> 6\. draw a boxplot for genes where the bayes mean = 0 and arithmetic mean > 0
<img width="1440" alt="zero_mean" src="https://user-images.githubusercontent.com/62498686/156893791-a41bd835-3c52-4507-897e-c5aca86ea6fc.PNG">

<img width="1440" alt="genes_with_zero_mean_in_bayes" src="https://user-images.githubusercontent.com/62498686/156893798-65da1c67-975a-417b-a85e-c50efc6a5419.PNG">

**Comment by Kamran-Khan96** [comment]
Obsolete
