### ISSUE TITLE
Optimise signature extraction memory consumption.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#37]

**Comment by stemangiola** [comment]
Hello @jianwu1, Kamran told me that your function for signature calculation uses 50+ Gb. 

We need to decrease this. 

This can be quite simple. For each function you might be creating several huge variables, as R is inefficient to clean the environment you need either 
- to rm() them as soon as you don't need any more, and run gc() in the line after
- Don't create variables if you don't need them
- make these variables smaller for example, just selecting 1, 2 columns you need rather than 10, 20

Let me know what you think.

**Comment by jianwu1** [comment]
> * to rm() them as soon as you don't need any more, and run gc() in the line after
> * Don't create variables if you don't need them
> * make these variables smaller for example, just selecting 1, 2 columns you need rather than 10, 20

I see. Thanks @stemangiola, I'll update the code in light of these suggestions.

**Comment by Kamran-Khan96** [comment]
Obsolete
