### ISSUE TITLE
Modularisation

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#4]
Gene marker identification
modularise  the functions into pipelines. Modules should take same type of input and produce same type of output.
Shiny app

**Comment by jianwu1** [comment]
Hi @stemangiola,

1. Modularisation is completed. All modules including scale_input_count(), generate_contrast(), do_ranking(), do_selection(), do_optimisation(), format_output(), are streamlined under the main() function.
2. Given the updated code, I tried to run pairwise.silhouette.non_hierarchy selection method, which is feasible now, but I got this error:
saying CPU time limit is reached.
![CPU time limit](https://user-images.githubusercontent.com/62498686/117522410-8c901300-aff6-11eb-8e6f-f8fb2beec506.PNG)
3. Here's the new summary bar plot and PCA plot for the best method:
![plot_zoom_png (9)](https://user-images.githubusercontent.com/62498686/117522489-0b854b80-aff7-11eb-94b5-3bf61dfe537c.png)
![plot_zoom_png (10)](https://user-images.githubusercontent.com/62498686/117522490-13dd8680-aff7-11eb-99f6-fba000bcc83b.png)
![plot_zoom_png (10)_0 195](https://user-images.githubusercontent.com/62498686/117522508-366f9f80-aff7-11eb-97e8-58149c416d41.png)

**Comment by stemangiola** [comment]
Amazing. Please implement scoring deconvolution method to replace siluette
deconvolution method.

Keep everything modular.

**Comment by Kamran-Khan96** [comment]
Resolved
