### ISSUE TITLE
Use/compare new method for signature selection

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#40]
Hello @Kamran-Khan96 , I completed the Bayes dataset, which should be better generalizable to unknown new query datasets. 

https://wehieduau-my.sharepoint.com/:u:/g/personal/mangiola_s_wehi_edu_au/EYGdKSDTAWxKvYKScXwE2KIBkC3oHQvMLR-jWk94y3uoWA?e=bNlC81

Jian wrote a testing/feature selection module that instead of using `test_differential_abundance` simply compares the credible intervals of genes between cell types, and ranks the gene markers based on the greatest distance between credible intervals. I am pretty sure you should be able to just replace the input dataset with the above one, and get an alternative feature list.

Please let me know if anything is not clear.

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,

I've run the code with this dataset with some modifications.


I have a question, you have a separate workflow of generating the bayes dataset, right? Because within this dataset, I'm missing my target cell types. So, the results also don't contain any information regarding those cell types.

**Comment by stemangiola** [comment]
I see. Yes please send me via Google drive the new samples. Also I remember Jian integrated many more T memory cells or something similar.

Could you send me the sample/cell-type counts so I compare with my local dataset?

**Comment by Kamran-Khan96** [comment]
Please find the updated counts file of Jian (contains my NK dataset too) here - 

https://unimelbcloud.sharepoint.com/:u:/t/BarrowLab/EYv4RBFNCwVLjHniEnjB_BsB_krFB8zvrAqgTp-mt7nS_g?email=mangiola.s%40wehi.edu.au&e=vARZIR

or

https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/counts_jian_v2.rds?csf=1&web=1&e=dGrD4d

**Comment by stemangiola** [comment]
Sorry a request. 

Could you create the union dataset of this

https://wehieduau-my.sharepoint.com/:u:/g/personal/mangiola_s_wehi_edu_au/EXtWtb3KlmdCoG6qN0cFXK4B1iebhq5CiLHyMi3yUfUFCw?e=94dXg1

With the one you have with all cell types (not your subset of 24 cell types). 
Also tell me how is the tree yaml for your NK branch.

I will repeat the Bayesian inference

**Comment by Kamran-Khan96** [comment]
I have made the union dataset with the one that you shared.


However, points to be noted, your dataset has been scaled and imputed already, whereas I have the dataset of raw counts. Also, I can't do the scaling and imputation before merging as I don't know your tree organization. So, I just took the counts, sample, symbol, cell_type, and database from your dataset and then did the union with the dataset I have.

I have also provided a separate dataset with the counts of samples and cell_type not included in your counts_imputed file. Maybe you'll be able to merge it with your raw count file.


Union dataset - https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/counts_file_v2.rds?csf=1&web=1&e=Uv4iKV

Dataset containing the new samples- https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/counts_dataset_not_in_counts_imputed.rds?csf=1&web=1&e=cBFYEA

**Comment by stemangiola** [comment]
Thanks. Yes you got it right. Indeed I will discard scaling and imputation.

**Comment by Kamran-Khan96** [comment]
I forgot to provide my current tree organization.

Here's my current tree.yaml file- https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/tree.yaml?csf=1&web=1&e=0FGd35

**Comment by stemangiola** [comment]
Hello Kamran, 

can you find at least 2 datasets that have bright and dim? they can be normalised counts as well.

**Comment by Kamran-Khan96** [comment]
Hi Stefano,

Updated files are here- 


Union dataset - https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/counts_file_v3.rds?csf=1&web=1&e=aAsE71

Dataset containing the new samples- https://unimelbcloud.sharepoint.com/:u:/r/teams/BarrowLab/Shared%20Documents/Computational%20Immunology%20Team/Kamran/count_database/counts_dataset_not_in_counts_imputed_v2.rds?csf=1&web=1&e=pilgVB

**Comment by Kamran-Khan96** [comment]
Resolved
