### ISSUE TITLE
Vignette for Bayes

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#48]
Hello @Kamran-Khan96,

some feedback on the signature selection for Bayes. I think that since Bayes input is quite different from the raw counts input, the `main` function (or its subfunctions) should be called in the backend, and we should have another cleaner dedicate interface (another function, see below)

In summary, rather than this code in the vignette

```r
library(here)

# Load the functions
source(here("dev/jian_R_files/cellsig_for_kamran.R"), local = knitr::knit_global())

# Load the count data and tree file
count = readRDS(here("dev/jian_R_files/test_count_data.rds"))

# Load tree
tree = yaml.load_file(here("dev/jian_R_files/test_tree.yaml")) %>% 
  as.Node

# Load the bayes count file
bayes = readRDS(here("dev/jian_R_files/test_count_bayes.rds"))  %>%

  # add sample column to bayes file
  inner_join(readRDS(here("dev/jian_R_files/bayes_add_sample.rds")))

signature_bayes = count %>%
  main(.sample = sample, .symbol = symbol, .count = count, .cell_type = cell_type,
       .is_hierarchy=FALSE,
       .tree = tree,
       .contrast_method = pairwise_contrast, .ranking_method = rank_bayes, .bayes= bayes,
       .selection_method = "silhouette", .reduction_method = "PCA", .dims=2, .discard_number = 10,
       .optimisation_method = "penalty",
       .is_complete = TRUE)
```

We should have

```r

marker_genes = 
  bayes_quantiles %>%
  get_markers_from_transcription_abundance_quantiles(
       .cell_type = cell_type,
       .symbol = symbol, 
       .lower_quantile = `10%`,
       .upper_quantile = `90%`,

      # Secondary arguments
       tree = NULL, # If tree is NULL we know that hierarchy is FALSE, so we simplify the interface
       contrast_method = pairwise_contrast, 
       selection_method = "silhouette", 
       reduction_method = "PCA", 
       dims=2, 
       discard_number = 10,
       optimisation_method = "penalty",
       is_complete = TRUE
  )
```

Let me know what you think and if you can implement it.

**Comment by Kamran-Khan96** [comment]
Thanks! Wonderful idea!

I'll look into this! Will keep you updated!

**Comment by Kamran-Khan96** [comment]
Hi Stefano,


I rechecked the workflow of this.


Even though, as you've mentioned, Bayes input is different from the raw count input, we can't just ignore the raw count data and its input for the Bayes approach as in the "Marker Selection" and subsequent steps, it takes scaled counts from the raw count input and merges it with Bayes markers for getting the optimized markers. 

What I can do is, make another dedicated function where we'll highlight the main input parameters of bayes and secondarily the input parameters of the raw counts data.


Let me know your thoughts.

Cheers,
Kamran

**Comment by stemangiola** [comment]
> "Marker Selection" and subsequent steps, it takes scaled counts from the raw count input and merges it with Bayes markers for getting the optimized markers

**I see, exactly what information takes from count data?** 

I would imagine that quantise should be enough for ranking genes. I suspect that the utilisation of raw counts is a historical connection as the role counts pipeline was designed first.

**Comment by Kamran-Khan96** [comment]
> **I see, exactly what information takes from count data?**

As we're using a reduction method for the doing the best marker selection, it requires "Scaled count" values for each selected marker genes, and samples.

> I would imagine that quantise should be enough for ranking genes. I suspect that the utilisation of raw counts is a historical connection as the role counts pipeline was designed first.
 
Yes, you're correct, ranking is done based on the quantile information, however, for the subsequent selection depends on the information of scaled and imputed raw count data.

**Comment by Kamran-Khan96** [comment]
To be specific, the scaled counts are required in the dimension reduction function, which  is inherently required for both Naive and Silhouette selections.

![image](https://user-images.githubusercontent.com/84835699/171075876-14949614-f07e-43d1-b487-d219f9dd5ece.png)

**Comment by stemangiola** [comment]
I see. OK let's then have a unique input that has boh counts as quantiles. 

```r
marker_genes = 
  counts %>%
  inner_join(bayes_quantiles, by = c("cell_type", "symbol")) %>%

  get_markers_from_transcription_abundance_quantiles(
       .sample = sample,
       .cell_type = cell_type,
       .symbol = symbol, 
       .count = count,
       .lower_quantile = `10%`,
       .upper_quantile = `90%`,

      # Secondary arguments
       tree = NULL, # If tree is NULL we know that hierarchy is FALSE, so we simplify the interface
       contrast_method = pairwise_contrast, 
       selection_method = "silhouette", 
       reduction_method = "PCA", 
       dims=2, 
       discard_number = 10,
       optimisation_method = "penalty",
       is_complete = TRUE
  )
```

Then in the backend you can re-derive ther bayes dataset doing bayes = distinct(!!.cell_type, !!.symbol, !!.lower_quantile, ...)

**Comment by Kamran-Khan96** [comment]
Great, I'll see to it.

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,

So, we won't be imputing and scaling the raw counts, right? If this is the case, then I'll have to make some changes in the workflow to ensure it doesn't rely on imputed and scaled counts.

But I think if we rely on the raw non-imputed and un-scaled counts, we might miss some information during the selection.

Let me know if I'm wrong.

**Comment by stemangiola** [comment]
Hello Kamran,

let's keep it simple, all the input column that you need, as before, just add the quantiles to the main input, rather than another input table.

In summary we should have just one ionput table with all information we need.

I did not mean to make you spend a lot of time on this sorry :) anyway a but cleaner interfacer is needed. After that I will use the function.

**Comment by Kamran-Khan96** [comment]
Sorry, my bad!

But when we merge the data into a single data, won't we miss some data? For instance- in the bayes quantile file, we have "immune cell" as cell_type and associated values. So, when we merge them, these values will be lost.  Maybe for the non-hierarchical approach they don't have any importance, but when we'll be doing the same workflow for hierarchical, we'll be missing those information.

I'm figuring something out, should fix the issue!

**Comment by Kamran-Khan96** [comment]
Hi Stefano,

I've made a function to work with a single count file. But the issue is I can't seem to feed the function the column names `10%` as it seems these are non-syntactic. Tried different things but I couldn't resolve it.

The simplest solution I made it renaming the column names of the bayes_quantile file to assign lower_quantile and upper_quantile columns before merging into a single count data.

I'm making a separate branch called (bayes_signature_from_quantile_function) with this fixes. 


Let me know if you're aware of a better solution.

**Comment by stemangiola** [comment]
You have to feed them as such, with angled quotes

\`10%\`

How were you able to solve the "immune_cell" issue? Maybe we can meet as soon as you can (I'm always in my zoom room) to finalise this issue.

When you have code you want me to test let me know.

**Comment by stemangiola** [comment]
Ok I think the old solution is still the best

- put dotted arguments only for column names
- 




```r

marker_genes = 
  counts %>%

  main(

       # MAIN arguments
       .sample = sample,
       .cell_type = cell_type,
       .symbol = symbol, 
       .count = count,

       # QUANTILE - These arguments point to the quantile_dataset input variable
       quantile_dataset = bayes_quantiles,
       .lower_quantile = `10%`,
       .upper_quantile = `90%`,

      # Secondary arguments
       tree = NULL, # If tree is NULL we know that hierarchy is FALSE, so we simplify the interface
       contrast_method = pairwise_contrast, 
       selection_method = "silhouette", 
       reduction_method = "PCA", 
       dims=2, 
       discard_number = 10,
       optimisation_method = "penalty",
       is_complete = TRUE
  )

```

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,


Updated function vignette is added in this branch [bayes_signature_from_quantile_function](https://github.com/stemangiola/cellsig/tree/bayes_signature_from_quantile_function)


Let me know if it doesn't work.

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,


The function is included in the vignette `signature_from_counts_and_tree.Rmd` in [bayes_signature_from_quantile_function](https://github.com/stemangiola/cellsig/tree/bayes_signature_from_quantile_function) branch.


The function is -
```{r}
marker_genes = 
  
  count %>%
  
  markers_from_transcription_abundance_quantiles(
    
    
    .sample = sample, 
    .symbol = symbol, 
    .count= count,
    .cell_type = cell_type,
    
    
    quantile_dataset = bayes_quantiles,
    lower_quantile = "10%",
    upper_quantile = "90%",
    
    
    tree = tree,
    is_hierarchy = FALSE,
    contrast_method = pairwise_contrast,
    selection_method = "silhouette", 
    reduction_method = "PCA", 
    dims=2, 
    discard_number = 10,
    optimisation_method = "penalty",
    is_complete = TRUE
  )
```

**Comment by Kamran-Khan96** [comment]
Obsolete
