### ISSUE TITLE
1- Pick manually signature size for every node (be your own optimisation method), and test CD4 PCA, does it look good.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#5]
Pick manually signature size for every node (be your own optimisation method), and test CD4 PCA, does it look good.

If this is true, we try to build a programmatic method that achieves the same selection.

First, check if increasing penalty achieves the knee identification for optimisation

IF NOT

Change optimisation method 
- kernel smooth (choose the right kernel)
- and identify 2nd derivatives

**Comment by stemangiola** [comment]
@jianwu1 I found this optimisation R script.

https://rdrr.io/github/agentlans/KneeArrower/man/findCutoff.html

See if it's any good

**Comment by stemangiola** [comment]
> I found this optimisation R script.

Sorry I think is not going what I though

![image](https://user-images.githubusercontent.com/7232890/120264954-46229100-c2e2-11eb-94f5-45b7682027bc.png)

**Comment by jianwu1** [comment]
Manual selection of optimal signature size:
![image](https://user-images.githubusercontent.com/62498686/120795465-dda31080-c57c-11eb-863f-3e820bfaa408.png)
![image](https://user-images.githubusercontent.com/62498686/120795553-fa3f4880-c57c-11eb-9219-f5a9acfc2c13.png)

![image](https://user-images.githubusercontent.com/62498686/120796100-bc8eef80-c57d-11eb-9462-e78edd2e03bb.png)
![image](https://user-images.githubusercontent.com/62498686/120796197-e0523580-c57d-11eb-87d8-0bd0b6747906.png)

![image](https://user-images.githubusercontent.com/62498686/120754680-5d66b600-c550-11eb-806f-13ed3bcc0321.png)
![image](https://user-images.githubusercontent.com/62498686/120754634-4a53e600-c550-11eb-9d2c-2a23186657d2.png)

![image](https://user-images.githubusercontent.com/62498686/120765248-5a71c280-c55c-11eb-9050-88a9b217e863.png)
![image](https://user-images.githubusercontent.com/62498686/120765979-1cc16980-c55d-11eb-9dad-965083fe7841.png)

![image](https://user-images.githubusercontent.com/62498686/120766549-af620880-c55d-11eb-8f8b-5cbd89ef152a.png)
![image](https://user-images.githubusercontent.com/62498686/120766707-d8829900-c55d-11eb-90a6-81de8d5838ed.png)

![image](https://user-images.githubusercontent.com/62498686/120767328-74aca000-c55e-11eb-9ced-7d959e99cd6a.png)
![image](https://user-images.githubusercontent.com/62498686/120767552-a02f8a80-c55e-11eb-9701-0f35a804d1bf.png)

![image](https://user-images.githubusercontent.com/62498686/120768082-25b33a80-c55f-11eb-9dcc-d2fc489a3fd3.png)
![image](https://user-images.githubusercontent.com/62498686/120768032-1af8a580-c55f-11eb-8d26-857f3586ce27.png)

![image](https://user-images.githubusercontent.com/62498686/120768902-f3eea380-c55f-11eb-9a9f-e7f97889ec0f.png)
![image](https://user-images.githubusercontent.com/62498686/120768986-079a0a00-c560-11eb-976f-a3fb4be7b547.png)

![image](https://user-images.githubusercontent.com/62498686/120769356-63649300-c560-11eb-9c2f-9cf9339f9d6d.png)
![image](https://user-images.githubusercontent.com/62498686/120769397-6cedfb00-c560-11eb-8ac6-bea7d4238400.png)

![image](https://user-images.githubusercontent.com/62498686/120773546-ca844680-c564-11eb-8203-866bfe6c24f4.png)
![image](https://user-images.githubusercontent.com/62498686/120773713-f1db1380-c564-11eb-998e-b2868a570c69.png)

![image](https://user-images.githubusercontent.com/62498686/120775297-6bbfcc80-c566-11eb-8636-d38d7d24d921.png)
![image](https://user-images.githubusercontent.com/62498686/120775480-9447c680-c566-11eb-90b1-ee72a4fd8dc3.png)

![image](https://user-images.githubusercontent.com/62498686/120775658-c3f6ce80-c566-11eb-9783-97c8134eb418.png)
![image](https://user-images.githubusercontent.com/62498686/120775850-f0124f80-c566-11eb-9f75-7cfdcb5965ca.png)

![image](https://user-images.githubusercontent.com/62498686/120776290-6ca52e00-c567-11eb-9b10-0f2fdbbf96c8.png)
![image](https://user-images.githubusercontent.com/62498686/120776487-a5450780-c567-11eb-98af-0119abed30b0.png)

![image](https://user-images.githubusercontent.com/62498686/120777424-9d399780-c568-11eb-8d70-24e12a4a80a2.png)
![image](https://user-images.githubusercontent.com/62498686/120777511-b2aec180-c568-11eb-852f-595858445caf.png)

**Comment by stemangiola** [comment]
Great.

> Visual selection of optimal signature size:

Did you mean manual selection?

Actually, I meant select all sizes, unite the whole signature and plot all nodes as you did now.

A tip, for level 1 you can just select 25-30 genes

**Comment by jianwu1** [comment]
> Actually, I meant select all sizes, unite the whole signature and plot all nodes as you did now.

Hi Stefano,

Can I ask what you mean by selecting all sizes and uniting the whole signature? I haven't combined nodal signatures as I did for CD4 before. Is that what you want? combine nodal signatures for each node and then plot PCA for each node?

**Comment by stemangiola** [comment]
> combine nodal signatures for each node and then plot PCA for each node?

Yes so in this case the signature should be 60 + 72 + ...

But then drawing PCA plots for each node. The goal is: can we pick an optimal signature size for each node, then when put together performs well for every single node?

Expect 60 markers for level 1 is a lot (maybe 30)

**Comment by jianwu1** [comment]
> > combine nodal signatures for each node and then plot PCA for each node?
> 
> Yes so in this case the signature should be 60 + 72 + ...
> 
> But then drawing PCA plots for each node. The goal is: can we pick an optimal signature size for each node, then when put together performs well for every single node?
> 
> Expect 60 markers for level 1 is a lot (maybe 30)

using manually selected signatures from mean_contrast.silhouette.hierarchy:

![image](https://user-images.githubusercontent.com/62498686/120875715-98202b00-c5f0-11eb-8113-533e9e2ba17d.png)
![image](https://user-images.githubusercontent.com/62498686/120875747-cbfb5080-c5f0-11eb-99f4-4ee26d4769c5.png)
![image](https://user-images.githubusercontent.com/62498686/120875784-f6e5a480-c5f0-11eb-9364-081dae11434f.png)
![image](https://user-images.githubusercontent.com/62498686/120875817-22688f00-c5f1-11eb-9476-bbd44a18d232.png)
![image](https://user-images.githubusercontent.com/62498686/120875843-43c97b00-c5f1-11eb-8f2b-d0573c738385.png)
![image](https://user-images.githubusercontent.com/62498686/120875870-5fcd1c80-c5f1-11eb-96b4-4c7017714c20.png)
![image](https://user-images.githubusercontent.com/62498686/120875895-868b5300-c5f1-11eb-9b12-c389ba3eb8f4.png)
![image](https://user-images.githubusercontent.com/62498686/120875957-b20e3d80-c5f1-11eb-8303-f814a2124980.png)
![image](https://user-images.githubusercontent.com/62498686/120876021-d4a05680-c5f1-11eb-8b3b-454297bfe7e8.png)
![image](https://user-images.githubusercontent.com/62498686/120876067-0fa28a00-c5f2-11eb-9c03-6961660ff472.png)
![image](https://user-images.githubusercontent.com/62498686/120876100-352f9380-c5f2-11eb-8a49-1a41ed96791e.png)
![image](https://user-images.githubusercontent.com/62498686/120876123-54c6bc00-c5f2-11eb-933a-ca6791185371.png)
![image](https://user-images.githubusercontent.com/62498686/120876152-77f16b80-c5f2-11eb-8765-59b28588bd92.png)
![image](https://user-images.githubusercontent.com/62498686/120876161-83dd2d80-c5f2-11eb-8f43-8a81c6ac9154.png)

![image](https://user-images.githubusercontent.com/62498686/120876523-817bd300-c5f4-11eb-9351-fb4bf5ad7e35.png)

**Comment by stemangiola** [comment]
Much better isn't it. What do you think?

Optimal signatures pairwise silhouette hierarchy

![image](https://user-images.githubusercontent.com/7232890/120876625-44fca700-c5f5-11eb-94d9-ade6ec5fc9d8.png)

Non-optimal pairwise silhouette hierarchy

![image](https://user-images.githubusercontent.com/7232890/120876654-72e1eb80-c5f5-11eb-8ad0-5d12522e9a62.png)

Now if you draw the boxplot (plus overlapping jitter points) for all methods (for this hierarchy pick the manual optimal signature) for all nodes (using complete signature as we discussed before) how do the result look. Did the hierarchy gained points over the others?

**Comment by stemangiola** [comment]
@jianwu1  do you want to meet now? Or tomorrow?

**Comment by jianwu1** [comment]
![image](https://user-images.githubusercontent.com/62498686/123667055-1e8cfd00-d87d-11eb-8465-3d422d22e0ef.png)
![image](https://user-images.githubusercontent.com/62498686/123667219-4a0fe780-d87d-11eb-84ea-7d27c490539b.png)
![image](https://user-images.githubusercontent.com/62498686/123667358-6e6bc400-d87d-11eb-91bc-40d77b43a3d3.png)

![image](https://user-images.githubusercontent.com/62498686/123667580-a115bc80-d87d-11eb-9fa9-7058e7089a87.png)
![image](https://user-images.githubusercontent.com/62498686/123667711-c1457b80-d87d-11eb-9d52-2632844bf460.png)
![image](https://user-images.githubusercontent.com/62498686/123667876-e89c4880-d87d-11eb-8c83-0f2f2c578207.png)

**Comment by jianwu1** [comment]
METHOD: mean_contrast.silhouette.hierarchy

![image](https://user-images.githubusercontent.com/62498686/124059706-dfbe9900-da6e-11eb-891e-9af8cf250015.png)
![image](https://user-images.githubusercontent.com/62498686/124061809-ec44f080-da72-11eb-9334-89c58788391b.png)


![image](https://user-images.githubusercontent.com/62498686/124059792-08469300-da6f-11eb-8335-126fbd11e785.png)
![image](https://user-images.githubusercontent.com/62498686/124061906-18f90800-da73-11eb-9c3c-59aa87966e83.png)


![image](https://user-images.githubusercontent.com/62498686/124059913-43e15d00-da6f-11eb-8523-3a7147e00e2a.png)
![image](https://user-images.githubusercontent.com/62498686/124061947-2d3d0500-da73-11eb-8a23-8d0bc358f06e.png)


![image](https://user-images.githubusercontent.com/62498686/124060176-d124b180-da6f-11eb-85d7-d46d63c736e9.png)
![image](https://user-images.githubusercontent.com/62498686/124061996-4940a680-da73-11eb-83df-440748927ef4.png)


![image](https://user-images.githubusercontent.com/62498686/124060238-f7e2e800-da6f-11eb-909e-16a5ec4860a5.png)
![image](https://user-images.githubusercontent.com/62498686/124062030-5c537680-da73-11eb-96e8-45c8cecc0f9e.png)


![image](https://user-images.githubusercontent.com/62498686/124060287-15b04d00-da70-11eb-9236-2e74d5d271da.png)
![image](https://user-images.githubusercontent.com/62498686/124062074-70977380-da73-11eb-9d51-43e92e42735e.png)


![image](https://user-images.githubusercontent.com/62498686/124060330-2cef3a80-da70-11eb-8a48-1f9c54a0bb4c.png)
![image](https://user-images.githubusercontent.com/62498686/124062104-8311ad00-da73-11eb-869e-eb1ac78c70f5.png)


![image](https://user-images.githubusercontent.com/62498686/124060388-4e502680-da70-11eb-9f97-0c5b096f7b0e.png)
![image](https://user-images.githubusercontent.com/62498686/124062148-945ab980-da73-11eb-929d-1a68757a65dd.png)


![image](https://user-images.githubusercontent.com/62498686/124060448-6a53c800-da70-11eb-89d3-3769ba20c5a2.png)
![image](https://user-images.githubusercontent.com/62498686/124062195-a6d4f300-da73-11eb-8efc-f363f788de6e.png)


![image](https://user-images.githubusercontent.com/62498686/124060500-85263c80-da70-11eb-86c7-6d4f9088cb2b.png)
![image](https://user-images.githubusercontent.com/62498686/124062238-b7856900-da73-11eb-8af4-bbb06ce3898d.png)


![image](https://user-images.githubusercontent.com/62498686/124060633-d20a1300-da70-11eb-8636-17f2ab9c1590.png)
![image](https://user-images.githubusercontent.com/62498686/124062282-cc61fc80-da73-11eb-85fa-782a31de84ed.png)


![image](https://user-images.githubusercontent.com/62498686/124060766-0bdb1980-da71-11eb-8650-f4457f513983.png)
![image](https://user-images.githubusercontent.com/62498686/124062320-dd127280-da73-11eb-9a3a-4a5fa3406389.png)


![image](https://user-images.githubusercontent.com/62498686/124060825-2ad9ab80-da71-11eb-9b08-1cd8e13396c6.png)
![image](https://user-images.githubusercontent.com/62498686/124062343-ec91bb80-da73-11eb-983d-f1704e9edc49.png)


![image](https://user-images.githubusercontent.com/62498686/124060978-6eccb080-da71-11eb-8d42-34ef832fb40a.png)
![image](https://user-images.githubusercontent.com/62498686/124062391-016e4f00-da74-11eb-9e6b-c8beb41eb727.png)

**Comment by jianwu1** [comment]
> Now if you draw the boxplot (plus overlapping jitter points) for all methods (for this hierarchy pick the manual optimal signature) for all nodes (using complete signature as we discussed before) how do the result look. Did the hierarchy gained points over the others?

Manual signature size selection of elbow points confers advantages over signature sizes selected by setting penalty rate to 0.2.
"op.man" refers to manually selected signature for the method: mean_contrast.silhouette.hierarchy.

![image](https://user-images.githubusercontent.com/62498686/124123040-238ac000-daba-11eb-9c2b-33cad548e0a4.png)
![image](https://user-images.githubusercontent.com/62498686/124123165-4e751400-daba-11eb-992c-a4c3483075fa.png)

![image](https://user-images.githubusercontent.com/62498686/124125144-9eed7100-dabc-11eb-8bde-cb34f21b157d.png)
![image](https://user-images.githubusercontent.com/62498686/124126221-cc86ea00-dabd-11eb-980b-8f284508270d.png)

**Comment by jianwu1** [comment]
Optimising signature size with penalty_rate:
![image](https://user-images.githubusercontent.com/62498686/124210961-b31e8600-db2f-11eb-82a8-5a5d8c07912f.png)
![image](https://user-images.githubusercontent.com/62498686/124211284-32ac5500-db30-11eb-90a9-bf56fee8dcaf.png)
![image](https://user-images.githubusercontent.com/62498686/124211178-08f32e00-db30-11eb-8c3c-aba29e9e6188.png)
![image](https://user-images.githubusercontent.com/62498686/124211391-5b344f00-db30-11eb-9a61-46506d9257e6.png)
![image](https://user-images.githubusercontent.com/62498686/124211496-87e86680-db30-11eb-81e9-c099849c86bf.png)
![image](https://user-images.githubusercontent.com/62498686/124211579-af3f3380-db30-11eb-9e04-a68566d4394e.png)
![image](https://user-images.githubusercontent.com/62498686/124211741-fd543700-db30-11eb-90b1-e544bd2c2fe9.png)
![image](https://user-images.githubusercontent.com/62498686/124211830-25dc3100-db31-11eb-9dba-e0f3964669bd.png)
![image](https://user-images.githubusercontent.com/62498686/124211961-6176fb00-db31-11eb-82d7-c9cfcc62992e.png)
![image](https://user-images.githubusercontent.com/62498686/124212210-e8c46e80-db31-11eb-863b-95685ae4949b.png)

**Comment by stemangiola** [comment]
Next things to do:

plot X: plot silhouette score, second derivative, first derivative, for every node, in one giant unique plot. For every node, you have two panels, one for silhouette + second derivative, and a panel below for the first derivative. In total, you will have 2 * 34 = 68 panels. 

For every penality_rate, build a plot X where you mark the "manual" and "penality-based automatic" and "1st derivative 45 degrees automatic" selected size (If I understood well, the manual selection will be a point on the silhouette score, the penality-based will be on the second derivative, and the first derivative method on the first derivative curve). You will have built 10 "plot X"

we will call "Performance-plot": Whenever you test the performance of any method of yours (e.g. the bar plots), instead you produce a two-panel figure: 
- boxplot of the final overall silhouette score
- boxplot of the deconvolution error
For this plot, whenever there is a boxplot with points being cell cluster/types, you should colour for cell type (as we discussed previously)

**Comment by jianwu1** [comment]
> plot X: plot silhouette score, second derivative, first derivative, for every node, in one giant unique plot. For every node, you have two panels, one for silhouette + second derivative, and a panel below for the first derivative. In total, you will have 2 * 34 = 68 panels.

Below is the summary plot X for mean_contrast.silhouette.hierarchy:
black line: raw silhouette score vs  MinMax rescaled size
black dots: estimated silhouette score from smoothing for 100 grid values 
blue dots: first derivative of the smoothed curve at each of the 100 grid values divided by 10 (1st deriv/10)
red dots: curvature rescaled to 0-1 with MinMax for the smoothed curve at each of the 100 grid values
The blue dot amongst black dots highlights the signature size selected by choosing point of which the 1st derivative is the closest to 1.
The red dot amongst black dots highlight the signature size selected by choosing point having maximum curvature.
![image](https://user-images.githubusercontent.com/62498686/124623963-cb8bf900-debf-11eb-8cc3-e41cd78497a6.png)

t_CD4 memory looks like that because there are not enough points for smoothing when the bandwidth = 0.05:
![image](https://user-images.githubusercontent.com/62498686/124627785-2f63f100-dec3-11eb-9f26-ac44dc025717.png)

I'll see which signature selection method is the best by boxplots of silhouette score and deconvolution score.

**Comment by jianwu1** [comment]
> For every penality_rate, build a plot X where you mark the "manual" and "penality-based automatic" and "1st derivative 45 degrees automatic" selected size (If I understood well, the manual selection will be a point on the silhouette score, the penality-based will be on the second derivative, and the first derivative method on the first derivative curve). You will have built 10 "plot X"

Below is a summary table comparing signature size selected by manual, 1st derivative, curvature, and penalty_rate=0.8 for mean_contrast.silhouette.hierarchy:
![image](https://user-images.githubusercontent.com/62498686/124624197-0726c300-dec0-11eb-90ae-215a419dabe8.png)

**Comment by stemangiola** [comment]
For CD8 I see the curvature gives good value IF you always discard a first
non convex pick. Pretty easy to check.  The highest value of the pick
should have a lower value at his left.

**Comment by stemangiola** [comment]
Also we could put a lower limit of 10 an call it a day

**Comment by jianwu1** [comment]
> For CD8 I see the curvature gives good value IF you always discard a first non convex pick. Pretty easy to check. The highest value of the pick should have a lower value at his left.

The signature size selected is sensitive to the level of smoothing:
**Bandwidth = 0.05**
![image](https://user-images.githubusercontent.com/62498686/124774313-0e61d580-df81-11eb-9709-1fe902579719.png)
![image](https://user-images.githubusercontent.com/62498686/124763739-a3f86780-df77-11eb-9400-07ed8194c3ef.png)

**Bandwidth = 0.1**
![image](https://user-images.githubusercontent.com/62498686/124777633-b2e51700-df83-11eb-9e6b-fb98504d22b4.png)
![image](https://user-images.githubusercontent.com/62498686/124777948-e9bb2d00-df83-11eb-9f66-0152334b924d.png)


**Bandwidth = 0.11**
![image](https://user-images.githubusercontent.com/62498686/124777323-787b7a00-df83-11eb-9f6d-2c08e63c475c.png)
![image](https://user-images.githubusercontent.com/62498686/124776827-1884d380-df83-11eb-81b6-113a65c7f465.png)

**Comment by jianwu1** [comment]
**pairwise.silhouette.hierarchy, bandwidth = 0.05 (Ignore manual sizes: manual selection not performed)**
![image](https://user-images.githubusercontent.com/62498686/124781820-0e64d400-df87-11eb-933d-5b23b7a52664.png)
![image](https://user-images.githubusercontent.com/62498686/124782350-83380e00-df87-11eb-95f8-568a02acc0b3.png)

**mean_contrast.naive.hierarchy, bandwidth = 0.05 (Ignore manual sizes: manual selection not performed)**
![image](https://user-images.githubusercontent.com/62498686/124783822-afa05a00-df88-11eb-92b1-7aa8af990073.png)
![image](https://user-images.githubusercontent.com/62498686/124783928-cb0b6500-df88-11eb-989d-a5311dd00e38.png)


**pairwise.naive.hierarchy, bandwidth = 0.05 (Ignore manual sizes: manual selection not performed)**
![image](https://user-images.githubusercontent.com/62498686/124784519-5ab11380-df89-11eb-9d02-4e5807f73ce3.png)
![image](https://user-images.githubusercontent.com/62498686/124784667-7c11ff80-df89-11eb-8d96-940ba3173102.png)

**Comment by jianwu1** [comment]
> we will call "Performance-plot": Whenever you test the performance of any method of yours (e.g. the bar plots), instead you produce a two-panel figure:
> 
> * boxplot of the final overall silhouette score
> * boxplot of the deconvolution error
>   For this plot, whenever there is a boxplot with points being cell cluster/types, you should colour for cell type (as we discussed previously)

silhouette says signature selected by curvature is better than manual or penalty_rate=0.2 but deconvolution says penalty_rate=0.2 is slightly better than curvature, and much better than manual...
![image](https://user-images.githubusercontent.com/62498686/125235304-994a2380-e325-11eb-9fb8-78f46645f99a.png)
![image](https://user-images.githubusercontent.com/62498686/125282225-79812280-e35a-11eb-97d2-9449427d8c4e.png)
![image](https://user-images.githubusercontent.com/62498686/125282854-2c518080-e35b-11eb-9d62-8d6949cee023.png)

**Comment by stemangiola** [comment]
Hello Jian, very well. I think there is room (maybe together with the cell-type specific signature production) for an interesting publication. Please create a function that create this plot, and inside use patchwork to combine plots (as already suggested). Please focus on the package/pipeline and provide the signature that I was inquiring about. Well done.Best wishes.Stefano  Stefano Mangiola | Postdoctoral fellowPapenfuss LaboratoryThe Walter Eliza Hall Institute of Medical Research+61 (0)466452544 From: jianwu1Sent: Monday, 12 July 2021 9:51 PMTo: stemangiola/cellsigCc: Stefano Mangiola; AuthorSubject: Re: [stemangiola/cellsig] 1- Pick manually signature size for every node (be your own optimisation method), and test CD4 PCA, does it look good. (#5) we will call "Performance-plot": Whenever you test the performance of any method of yours (e.g. the bar plots), instead you produce a two-panel figure:boxplot of the final overall silhouette scoreboxplot of the deconvolution errorFor this plot, whenever there is a boxplot with points being cell cluster/types, you should colour for cell type (as we discussed previously)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jianwu1** [comment]
compare all methods using curvature optimisation
silhouette score:
![image](https://user-images.githubusercontent.com/62498686/126245674-41380eb0-8d38-4bf9-9356-c28bc6202be3.png)

deconvolution:
![image](https://user-images.githubusercontent.com/62498686/126248219-a4c0647d-2178-4a72-ba89-42f60cc2f4f0.png)
![image](https://user-images.githubusercontent.com/62498686/126248527-4317ff77-c063-4411-9a44-0b064b7a41dc.png)
 
Using optimisation by curvature doesn't apply to naive signature selection methods because the silhouette score vs signature size trend doesn't have a logarithmic shape.

**Comment by Kamran-Khan96** [comment]
Obsolete
