### ISSUE TITLE
reproduce the bar plots with new PCA parameters.(top=Inf, scale=FALSE).

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#6]

**Comment by jianwu1** [comment]
Hi Stefano,
Here are plots comparing all methods, for which scores are calculated using the new parameters (top=Inf, scale=FALSE). Although all methods are better than cibersortx in terms of silhouette score and deconvolution MSE. The ranking order for all methods is different with respect to the two metrics.

![image](https://user-images.githubusercontent.com/62498686/121674727-c53f7280-caf5-11eb-8250-c031240d1ff6.png)
![image](https://user-images.githubusercontent.com/62498686/121679300-89a7a700-cafb-11eb-8766-dffdc0a213f2.png)

![image](https://user-images.githubusercontent.com/62498686/121675246-82ca6580-caf6-11eb-9f65-4d64eb7f669f.png)

**Comment by stemangiola** [comment]
Amazing hierarchical seems to pay off. Can you show

Pca for hierarchical siluette new
Box plot of those two bar plots.

Very promising!

**Comment by jianwu1** [comment]
> Can you show Pca for hierarchical siluette new Box plot of those two bar plots.

Boxplot for silhouette score (each point is the average silhouette score for a cell type/cluster, there are 36 cell types/points for each method):
![image](https://user-images.githubusercontent.com/62498686/123548932-40697f80-d7aa-11eb-9c60-f337de1e82ca.png)

**Comment by Kamran-Khan96** [comment]
Resolved
