### ISSUE TITLE
Goals for final figures

### ISSUE THREAD

**Issue by Kamran-Khan96** [stemangiola/cellsig#63]
Hi @stemangiola,

These are goals we currently have-

Ways to reach the goals for the final figure:

1. Heatmap with the markers to see if cellular hierarchy has been addressed ( will try to do by 05-08-22)
    
- Generate the signature with hierarchy
- construct the signature matrix
- create heatmap with the hierarchy-based markers, and compare with non-hierarchy markers 

2. Benchmark with signatures of different sizes (will try to do by 12-08-22)

- create the signatures with different marker sizes (like the approach previously done for non-hierarchy) 
- benchmark by deconvolution and create boxplots of error values

3. Benchmark with gene perturbation routine (will try to do by 19-08-22)

- create signatures after randomly perturbing a number of markers
- do the benchmark and create boxplot of error values

**Comment by stemangiola** [comment]
Thanks Kamran,

can you please 
- order your points from the easiest to the hardest
- put under each point the steps you need to do to achieve them
- put rough timelines for each of the three points so to organise your work?

**Comment by Kamran-Khan96** [comment]
Resolved
