### ISSUE TITLE
Figures and other files for the manuscript

### ISSUE THREAD

**Issue by Kamran-Khan96** [stemangiola/cellsig#65]

**Comment by Kamran-Khan96** [comment]
Progress so far-

We have the following figures- 

1. Beeswarm plot showing the markers identified from bayesian estimated data are more uniform than cibersortx markers.
2. Boxplots showing - If we use simulated data from bayesian estimation, the signatures with smaller sizes performs better than the generic cibersortx signatures, meaning smaller signature obtained from the estimated data could be more specific.
3. Boxplots showing- cibersortx outperforms cellsig signatures (non-hierarchical)
4. Error boxplots showed that using a hierarchical framework for cibersortx doesn't actually performs better than the default cibersortx signature.
5. Updated dimension plots (PCA) showed that, cibersortx might actually can address the difference between stromal and immune cells.


Next to-dos-

# 
#

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,

These are the To-dos that we've talked about-

For Manuscript-

1. Send the figure to Stefano
2. Start writing the rest of the manuscript
- Complete the method, results & discussion, and conclusion
- update the table
- compile the supplementary resources
- update the introduction (where necessary)


For Shiny App- 

1. Add the quantiles values from bayes-data within the violin plot (like an error bar, 50% and 90% values to be indicated in the background maybe with a different color)
2. Add a separate tab for downloading the expression data.
3. Host the app to the server.


Let me know if I've missed anything.

**Comment by stemangiola** [comment]
Great, in the shiny PCA green coloured use

`scale_color_log()`

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola ,


I have updated the app with the changes you wanted to add.


Please have a look by running the `app_v3.R` file after you've pulled the updates.

**Comment by stemangiola** [comment]
Thanks I get 

```

Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data_for_download.RData', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
```

**Comment by Kamran-Khan96** [comment]
Yeah, sorry! I messed up a little bit. Fixing the problems now. Will get back to you soon.

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola ,


sorry for the mess up!


I've moved the files to my `Kamran` branch. You can get the files from here- https://github.com/stemangiola/cellsig/tree/Kamran/dev/shiny_kamran

Run the app by running `app.R`

**Comment by stemangiola** [comment]
Hello,

please see feedback

https://unimelb.zoom.us/rec/share/Ea3sY2g9wZeRBu7yKH-zz42VK-sHbrPRV1_EH3hpptk3GjH55C6RLvcqLLQVr5sg.rO0IQklyk6kWnimo 
Passcode: w0HY*Vop

**Comment by Kamran-Khan96** [comment]
Ok sir!

Understood. I'll try to implement those things. Will keep you updated.

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,


All the updates have been implemented.


Please have a look and let me know your thoughts.


Cheers,
Kamran

**Comment by stemangiola** [comment]
Great! consider this done and move on.

If you have any question on the presentation of Wed let me know.

**Comment by Kamran-Khan96** [comment]
> Great! consider this done and move on.

Cool!

> If you have any question on the presentation of Wed let me know.

Sure, I will.

**Comment by Kamran-Khan96** [comment]
Note for Kamran-

- Use colour palette of the shiny app (which should be the same of the present figures)

- Place the legends on the bottom
- Chose for the example panel the same cell type, showing the top N genes for cibersort and cibersort+bayes, which showcases the presence of outliters
- Use same cell type labels already present in the other figures that I gave to you
- Use Stefano's multipanel theme
 
```{r}
source("https://gist.githubusercontent.com/stemangiola/fc67b08101df7d550683a5100106561c/raw/a0853a1a4e8a46baf33bad6268b09001d49faf51/ggplot_theme_multipanel")

Ggplot() + theme_multipanel

```

Use patchwotk to compose your 4 panel figure. I give you an example below
 

```{r}

library(patchwork)

p =

(

  # Introduction, before model

  plot_tree /

  # Cartoon of the model

  (plot_database_histo | plot_cell_type_info| plot_double) /

  pca_plot

)+

  # Style

  plot_layout(guides = 'collect', heights = c(1,1,1)) + plot_annotation(tag_levels = c('A')) &

  theme( plot.margin = margin(0, 0, 0, 0, "pt"), legend.position = "bottom")

```

**Comment by Kamran-Khan96** [comment]
To-dos for Kamran:

1. Create signatures for each hierarchical level (level 1, 2, 3, 4) (with optimum signature size) 
2. Create a new tab for the downloading of the signatures
3. (Optional) Generate a benchmarking plot to back up the preferred signature size selection
4. Update the manuscript text


Update Figure 4: **(DONE)**

1. Reorganise the figures and color the boxplots (instructions here- https://unimelb.zoom.us/rec/share/eyI5_nL-rpxdTVj304hDfwo9l1jmF31TwG0kBTbZCUHqpgusk6IVEFmDnrH_L1GR.7OXypbDgRW5z_6Ol, pass r2?^t2WT)

2. perform a linear regression on the 6 points, and put the adjusted pvalue on the plot?
hint: lm(mean_error ~ signature_size, data = 6_points)


- _write in the conclusion that signature size is important ..., therefore it is key to optimise information content at the top rank positions, that's why our improvements are good (obviously written much better)_ **Done**

- _can we encode the origin ("tissue" or otherwise) in the metadata excel supplementary table, rather than here?_

-_We procured the raw read counts of the transcripts for most datasets (n=XXX) with an exception for a few (n=XXX) datasets, which only contained the normalised read counts_


Update App Naming, Bayes file, enrich method text.

**Comment by Kamran-Khan96** [comment]
Resolved
