### ISSUE TITLE
Implement shiny app in the WEHI servers

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#66]
- [x] Test shiny app locally with your data
- [x] test ap locally and improve speed and stability
- [x] organise the transfer of the app into WEHI server (directory in WEHI machine)
- [x] test app remotely, and improve performance if needed

**Comment by stemangiola** [comment]
Here the original app was pulled off the remote server because nobody could conclude the implementation.

/stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/app_for_Kamran/ShinyApps

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola,

Apologies for the delayed response.

I have some queries-

1. Should I scale and Impute the missing abundances using hierarchical approach to generate the expression data frame?

2. It's not clear how Jian previously generated the PC values. Should I use the whole data for PCA and generating the PC values?

3. Should I request for the hosting of the app? or you should do it? Does it need to be done now or we can do it after checking it out locally?

Cheers,
Kamran

**Comment by stemangiola** [comment]
> 1. Should I scale and Impute the missing abundances using hierarchical approach to generate the expression data frame?

scale yes impute no, there will be some genes will fewer data, which is the reality.



> 2\. It's not clear how Jian previously generated the PC values. Should I use the whole data for PCA and generating the PC values?

You should use the signature genes



> 3\. Should I request for the hosting of the app? or you should do it? Does it need to be done now or we can do it after checking it out locally?

Do things in parallel, proceed with request and test locally at the same time.

**Comment by Kamran-Khan96** [comment]
> _scale yes impute no, there will be some genes will fewer data, which is the reality._

- Understood

> _You should use the signature genes_

- Which set of signature genes to use? As you know I currently have multiple sets of signature genes (a bunch from the cibersortx (of different sizes) and 1 from non-hierarchical cellsig)

> _Do things in parallel, proceed with request and test locally at the same time._
- Understood

**Comment by stemangiola** [comment]
> * Which set of signature genes to use? As you know I currently have multiple sets of signature genes (a bunch from the cibersortx (of different sizes) and 1 from non-hierarchical cellsig)

The one that gives the best PCA. For the sake of development don;t spend too much time on this choice.

**Comment by Kamran-Khan96** [comment]
> _The one that gives the best PCA. For the sake of development don;t spend too much time on this choice._

ok, understood!

**Comment by Kamran-Khan96** [comment]
Notes for Kamran-

[1] https://wehieduau.sharepoint.com/sites/rc2/SitePages/Shiny-Apps-Hosting.aspx

[2] https://wehieduau.sharepoint.com/sites/rc2/SitePages/Setting-up-Shiny-app.aspx

**Comment by Kamran-Khan96** [comment]
Updated files for testing the app have been uploaded here- https://github.com/stemangiola/cellsig/tree/updated_shiny_app_files/dev/shiny_kamran/ShinyApps/shiny_pub/v2

**Comment by stemangiola** [comment]
Thanks. Is any way we can see the shiny app live?

**Comment by Kamran-Khan96** [comment]
> Thanks. Is any way we can see the shiny app live?
- Yes if we want to see it live locally.

1. You can just switch to the branch "updated_shiny_app_files" and locate the "app_v2.R" file and open it.
2. Then simply just run the app.
![image](https://user-images.githubusercontent.com/84835699/188368509-4ea0fbaf-e1ca-478b-b080-5ce5447a015c.png)
3. Then you can just open it on browser and navigate as necessary.
![image](https://user-images.githubusercontent.com/84835699/188368640-0467588c-81a2-45f5-87ff-652e50d696f7.png)

**Comment by Kamran-Khan96** [comment]
@stemangiola ,

Do you want me to publish it on [shinyapps.io](https://www.shinyapps.io/)? If we publish it here, maybe It'll be open for everyone. I'm not sure.

**Comment by stemangiola** [comment]
> @stemangiola ,
> 
> Do you want me to publish it on [shinyapps.io](https://www.shinyapps.io/)? If we publish it here, maybe It'll be open for everyone. I'm not sure.

Are you able to publish on WEHI servers? How complicated is it to publish - edit - and publish again?

What would the public URL be of that WEHI app?

**Comment by Kamran-Khan96** [comment]
> Are you able to publish on WEHI servers?

Yes, as soon as they finish processing my request and allocate me a space. So, I can not publish this until that.

> How complicated is it to publish - edit - and publish again?

It should be fairly easy. I just need to transfer the files to the app directory. I think you can simply update the files and your app.R data as many times as you want, you just need to replace the old files.

> What would the public URL be of that WEHI app?

If we look at Julie's example, it should look something like- https://shiny.wehi.edu.au/iskander.j/testapp/

You can see the details from here- https://wehieduau.sharepoint.com/sites/rc2/SitePages/Setting-up-Shiny-app.aspx

**Comment by stemangiola** [comment]
Maybe at this stage, it would be worth publishing it on WEHI, so I can give feedback on the actual website.

**Comment by Kamran-Khan96** [comment]
> Maybe at this stage, it would be worth publishing it on WEHI, so I can give feedback on the actual website.

Ok, so we have to wait for the access then. And yes, I lot can vary between the local hosting and web-hosting. If you have any suggestion on anything (by looking at the local-hosting, as it'll be essentially the same), let me know.

**Comment by Kamran-Khan96** [comment]
Resolved
