### ISSUE TITLE
For each dataset, we want to test whether integration is needed across samples, or it is NOT needed.

### ISSUE THREAD

**Issue by XpelC** [stemangiola/cellsig#68]
We get SCT from each dataset, and plot UMAP of all samples in a dataset. If colouring by sample we see that all samples overlap, this means that we don't need integration across those samples.

The result is:

for which of those 5 datasets samples do not need to be integrated.

Paste below 5 UMAPs coloured by sample

**Comment by XpelC** [comment]
> for which of those 5 datasets samples do not need to be integrated.

1. EGAS00001005115_final
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/46272115/189649527-9b0646fb-502b-4527-a3e4-4b207713b2f5.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/46272115/189775473-10004294-e28a-492f-a2c8-aa243f5321aa.png">


2. EGAS00001005787_final
<img width="1030" alt="Screen Shot 2022-09-12 at 10 09 35 PM" src="https://user-images.githubusercontent.com/46272115/189649717-40ba1b7e-5dc0-4dc7-bf65-2610f350411a.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/46272115/189775701-1bf989c5-b62e-4856-8281-587d04932347.png">


3. GSE137829_final
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/46272115/189649807-68317194-fa95-46a7-9368-63d37a5c141a.png">

4. GSE141445_final 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/46272115/189650024-d2e3f4d6-108d-4ece-9165-41ee8c27ce14.png">

5. GSE176031_final
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/46272115/189650178-51584062-cffb-41b9-afb8-40fbf4e0418a.png">

**Comment by stemangiola** [comment]
- this dataset `GSE137829_final` need integration by sample.

- `EGAS00001005115_final 1` What are the above unique clusters? It is a bit peculiar

**Comment by XpelC** [comment]
1. datasets need to be integrated by sample
EGAS00001005115
EGAS00001005787
GSE137829
GSE141445_final

2. datasets might not need integration
GSE176031
