### ISSUE TITLE
3- After the full pipeline will be ready, please provide the signature for the attached differentiation tree and your new signature database.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#7]
Here the file

[tree.zip](https://github.com/stemangiola/cellsig/files/6698809/tree.zip)

See what utilities you might need to use an external data.tree/dendrogram file. Most likely I have functions ready for whatever you need. So as soon as you analyse the problem and the needs (if any), let meet.

**Comment by stemangiola** [comment]
Hello Jian,

I see that the tree and the cell types of your output differ

![image](https://user-images.githubusercontent.com/7232890/126260336-97b819e4-d5bd-4498-9291-8d161e6e4d1f.png)

**Comment by jianwu1** [comment]
> I see that the tree and the cell types of your output differ

Hi Stefano,

Sorry. I checked the code and found that the input counts data was not consistent with the new tree structure. I don't know why but maybe I copied what was in the global environment while running the job...

I'm running the code again.

**Comment by jianwu1** [comment]
Hi Stefano,

Can I ask what hk600 is? I get this error when trying to organise the data:
![image](https://user-images.githubusercontent.com/62498686/128018008-bfde3a5e-8277-41d2-bd9e-6150aa496956.png)

Input signatures look like this:
![image](https://user-images.githubusercontent.com/62498686/128018142-9ba77943-03a9-4660-913d-82f08d91db6c.png)

Kind regards,

Jian

**Comment by stemangiola** [comment]
Mm hk600 is house keeping genes. I did nor remember my script used it.
Please tell me what function fails and I will check

**Comment by stemangiola** [comment]
Also please look for thaT file in the repostory.  Maybe is already in there.

**Comment by jianwu1** [comment]
> Mm hk600 is house keeping genes. I did nor remember my script used it. Please tell me what function fails and I will check

Hi Stefano,
It's this function below. Debugonce shows that the error happens in the second step filtering house keeping genes:
`
infer_sequencing_depth_bias = function(counts, shards = 10){
  
  model_input = 
    counts %>%
    
    filter(level_1 %>% is.na %>% `!`) %>%
    mutate(cell_type = level_1) %>%
    
    # Get only house keeping genes
    filter(symbol %in% hk600) %>%
    
    # Add sample indexes
    nest(data = -sample) %>%
    rowid_to_column(var = "S") %>%
    unnest(data) %>%
    
    # Add sample indexes
    nest(data = -symbol) %>%
    rowid_to_column(var = "GM") %>%
    unnest(data) 
  
  # Input data
  GM = model_input %>% distinct(symbol) %>% nrow()
  S = model_input %>% distinct(sample) %>% nrow()
  CL = model_input %>% nrow
  
  counts_linear = model_input %>% pull(count)
  GM_to_counts_linear = model_input %>% pull(GM)
  S_linear = model_input %>% pull(S)
  
  # Non centered
  lambda_mu_prior = c(8, 2)
  lambda_sigma_prior =  c(log(3.3) , 1)
  lambda_skew_prior =  c(-2.7, 2)
  sigma_intercept_prior = c(1.9 , 0.5)
  
  Sys.setenv("STAN_NUM_THREADS" = shards)
  
  fit = 
    vb_iterative(
      #stanmodels$ARMET_ref,
      rstan::stan_model("inst/stan/infer_exposure.stan"),
      output_samples = 500,
      iter = 50000,
      tol_rel_obj = 0.01,
      algorithm = "meanfield", data = list(
        shards = 10,
        
        GM = model_input %>% distinct(symbol) %>% nrow(),
        S = model_input %>% distinct(sample) %>% nrow(),
        CL = model_input %>% nrow,
        
        counts_linear = model_input %>% pull(count),
        GM_to_counts_linear = model_input %>% pull(GM),
        S_linear = model_input %>% pull(S),
        
        # Non centered
        lambda_mu_prior = c(8, 2),
        lambda_sigma_prior =  c(log(3.3) , 1),
        lambda_skew_prior =  c(-2.7, 2),
        sigma_intercept_prior = c(1.9 , 0.5)
        )
    )
 
  fit %>%
    summary_to_tibble("exposure_rate", "S") %>%
    filter(.variable != "exposure_rate_minus_1") %>%
    left_join(
      model_input %>% distinct(sample, S),
      by="S"
    ) %>% 
    select(sample, exposure_rate = mean) %>%
    right_join(counts, by="sample")
}
`

**Comment by stemangiola** [comment]
I have added the necessary to read house keeping system, please review my commit, and pull from the repository, still data-exploration branch.

https://github.com/stemangiola/cellsig/commit/5647dee56be2f5648b8f3a1b949636b6a14dde93

**Comment by stemangiola** [comment]
However you don't need necessarily to run `infer_sequencing_depth_bias` to apply your pipeline, is needed though for the bayesian inference.

**Comment by stemangiola** [comment]
Hello @jianwu1 ,

while the table you produce is useful to you, 

![image](https://user-images.githubusercontent.com/7232890/129282617-5b78a736-4c78-4d2c-af9e-6ed8a1a5b585.png)


the output of the pipeline should be 2 dataframes with the following columns

1) Cell type transcrptomes (forget about signatures)
```r
cell_type (~ 30) | gene (~ 20000) | median_scaled_abundance (integer)
```

2) Signature genes
```r
gene (~ 200) |  target_cell_type | against_cell_type | rank | cell_differentiation_level
CD3G            | immune_cell      | all                         | 1     | 1
CD4               |  immune_cell      | all                        | 2     | 1
CD4               | t_Cell                  | b_Cell                  | 1      | 2
CD4               | t_Cell                  | natural_killer       | 1      | 2
```

For pairwise, I don't remember which we chose.

In this way, I would have 
- the full transcriptome of all cell types if I ignore the marker column 
- the marker list (filtering for markers != NA), 
- the marker directionality (if I unnest the marker column)
- I can ask what are the NK markers (if I unnest marker column, filter for target_cell_type =="nk")

With this dataset I will be able to integrate your work also in a publication I am doing, otherwise is not possible

**Comment by stemangiola** [comment]
Hello @jianwu1,

for the database you gave me, I see two strange things

1) I see ~900 samples instead of ~1200 that you showed me this week
2) I see that some genes are not present in all cell types. Just to make sure, you do this filtering after creating the database, for doing feature selection right?

```r
ref %>% nest(data = -symbol) %>% mutate(num_cell_types = map_int(data, ~ .x %>% distinct(cell_type) %>% nrow())) %>% filter(num_cell_types == max(num_cell_types)) %>% unnest(data)
# A tibble: 489,636 x 5
   symbol cell_type                  count is_marker num_cell_types
   <fct>  <fct>                      <dbl> <lgl>              <int>
 1 A1BG   b_cell                     101   FALSE                 29
 2 A1BG   b_memory                    68   FALSE                 29
 3 A1BG   b_naive                     99.5 FALSE                 29
 4 A1BG   dendritic_myeloid           19   FALSE                 29
 5 A1BG   dendritic_myeloid_immature  25   FALSE                 29
 6 A1BG   dendritic_myeloid_mature    70   FALSE                 29
 7 A1BG   endothelial                 44   FALSE                 29
 8 A1BG   eosinophil                   3   FALSE                 29
 9 A1BG   epithelial                  30   FALSE                 29
10 A1BG   fibroblast                 216   FALSE                 29
# … with 489,626 more rows
> ref
# A tibble: 1,408,049 x 4
   cell_type symbol     count is_marker
   <fct>     <fct>      <dbl> <lgl>    
 1 b_cell    5_8S_rRNA   1    FALSE    
 2 b_cell    5S_rRNA     4.90 FALSE    
 3 b_cell    7SK         2.83 FALSE    
 4 b_cell    A1BG      101    FALSE    
 5 b_cell    A1BG-AS1  202.   FALSE    
 6 b_cell    A1CF        1    FALSE    
 7 b_cell    A2M         5    FALSE    
 8 b_cell    A2M-AS1     6    FALSE    
 9 b_cell    A2ML1       3    FALSE    
10 b_cell    A2ML1-AS1   1    FALSE    
# … with 1,408,039 more rows
```

**Comment by jianwu1** [comment]
> 1. I see ~900 samples instead of ~1200 that you showed me this week
> 2. I see that some genes are not present in all cell types. Just to make sure, you do this filtering after creating the database, for doing feature selection right?

Hi @stemangiola,
1. I'll check the number of samples.

2. counts are a direct binding of the raw data and have not being rectangularised. In the preprocessing step, genes are filtered so that they are present in all cell types.

3.  I've been trying to incorporate contrast information in the function so that I can get signatures for all cell types rather than just nodal cell types.

**Comment by jianwu1** [comment]
> 1. I see ~900 samples instead of ~1200 that you showed me this week

Hi @stemangiola,

I think this is because samples for level_5 cell types are filtered by tree_and_signatures_to_database:
```
counts =  
  
  # Merge dataset
  counts_first_db_raw %>%
  bind_rows(counts_second_db_raw) %>% 
  bind_rows(counts_third_db_raw) %>%
  select(sample, cell_type, symbol, count, database) %>%
  
  # Add tree structure
  tree_and_signatures_to_database(tree, ., sample, cell_type, symbol, count) %>% 
  
  # Infer exposure rate  and scale
  infer_sequencing_depth_bias(hk600 = readr::read_csv("dev/hk_600.txt", col_names = FALSE) %>% pull(X1))
```
In counts.rds where there are 5 levels, there are 1200 samples:
![image](https://user-images.githubusercontent.com/62498686/129727386-e3aadf9a-e736-44c4-84e5-bf20441a676c.png)

I suppose level_5 cell types are not automatically included in the immediate parent level when creating a data rame (level_1|level_2|level_3...) based on the tree. I think if I manually change cell types such as "t_helper_1", "t_helper2" to "t_helper" in the counts data, there would be the same number of samples.

I guess we'd lose samples when we completely remove a whole level from the tree, but it shouldn't be a problem if we simplify other branches but keep the branch of interest to the highest level.

**Comment by stemangiola** [comment]
I see. I hope we are not loosing those samples we got the database 3 for. For examples DC.

**Comment by stemangiola** [comment]
Another option is to give me the whole counts and I will filter on level 4 instead than cell_type.

**Comment by jianwu1** [comment]
> I see. I hope we are not loosing those samples we got the database 3 for. For examples DC.

The highest level for DC cell types are level_4 so they should be there.

**Comment by jianwu1** [comment]
> Another option is to give me the whole counts and I will filter on level 4 instead than cell_type.

Ok. Yeah, this solves the problem.

**Comment by jianwu1** [comment]
> Another option is to give me the whole counts and I will filter on level 4 instead than cell_type.

Hi @stemangiola ,

In this case, do you want signature obtained from counts_stefano_tree.rds or signature obtained from counts.rds %>% select(- level_5) ?

Kind regards,

Jian

**Comment by stemangiola** [comment]
All good for this task. I'm already using the counts. Thanks. You will be
included in this publication. And maybe in future one from another
collaboration.

**Comment by stemangiola** [comment]
Hello @jianwu1,

can I ask you to provide me with another signature given my tree (maybe make an R script that does that, so you can execute it multiple times when needed, with Rscript ...)

Basically, because my deconvolution algorithm works hierarchically as well, I don't think I need optimisation. That is, I can have more markers for each level because I analyse each level separately.

Is it hard for you to run the same pipeline with optimisation off, so considering more markers toward the plateau of silhouette score (in the silhouette curve), without exaggerating of course.

I'm looking forward to hearing from you.

**Comment by jianwu1** [comment]
> with optimisation off

Hi Stefano,

I'm executing the R script as a job now. optimisation is turned off. Do you want to do optimisation with penalty=0.2 after obtaining the unoptimised result?

The method stream is:  hierarchical, mean_contrast, edgR, logFC, silhouette:
`readRDS("/stornext/Home/data/allstaff/w/wu.j/Master_Project/cellsig/dev/counts_stefano_tree.rds") %>% 
  main(.contrast_method=mean_contrast, .ranking_method=rank_edgR_quasi_likelihood, 
       .rank_stat = "logFC", .selection_method = "silhouette", .optimisation_method = NULL,
       .is_complete = TRUE) %>% 
  saveRDS("/stornext/Home/data/allstaff/w/wu.j/Master_Project/cellsig/dev/signature_stefano_unoptimised.rds", 
          compress = "xz")`

**Comment by jianwu1** [comment]
Also, I don't know if I could ask you something about the SLURM_benchmark_pipeline.sh file on zoom.

**Comment by stemangiola** [comment]
Hello Jian,

for my personal markers I would use

- hierarchical
- mean_contrast
- robust_edgeR

what would `penalty=0.2` do? I don't need to optimise, but not to consider all markers either, I need to stop closer to the plateau, rather than stop as soon as we can.

Still, for each level, we have to check that the node would have selected similar number of transcripts. To avoid that for example for level 3 we have 80 markers for CD4 and 2 for nk_activated, if you know what I mean.

**Comment by stemangiola** [comment]
> Also, I don't know if I could ask you something about the SLURM_benchmark_pipeline.sh file on zoom.

Sure I'm in now.

**Comment by Kamran-Khan96** [comment]
Resolved
