### ISSUE TITLE
Note: A possible alternative to ellipse plotting or ellipse-based calculation

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#8]
Poligon outer tracing

![image](https://user-images.githubusercontent.com/7232890/123203157-3e2cca00-d4f9-11eb-9831-f70ecaf7b35d.png)

I found it on a random page that does not tell how to make it

https://ggplot2.tidyverse.org/articles/extending-ggplot2.html#creating-a-new-geom-1

 but I'm sure this can be found already done

**Comment by Kamran-Khan96** [comment]
Obsolete
