### ISSUE TITLE
Generate at least 100 mixtures for each method and calculated the average MSE for all methods; compare all methods in terms of average MSE from 100 mixtures;

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/cellsig#9]

**Comment by jianwu1** [comment]
Hi Stefano,

I changed `gather` to `pivot_longer` but I found that sampling sample names takes the longest time in function `generate_mixture_from_proportion_matrix`.  It is however necessary for `left_join` in step3 in the screenshot to join the input dataframe by cell type and sample with the proportion data frame:
![image](https://user-images.githubusercontent.com/62498686/123378226-ce3d4300-d5cf-11eb-8724-4eef06813dfb.png)

**Comment by jianwu1** [comment]
Hi Stefano,

This is the macro-averaged MSE calculated from 100 mix matrices for each of the eight methods, and the hierarchical approach with silhouette selection exhibits stable advantage:
![image](https://user-images.githubusercontent.com/62498686/123438877-812f9000-d614-11eb-9866-2b9aecb27e9c.png)
All other approaches however, do not outperform cibersortx in terms of deconvolution MSE or at least do not give stable advantage over cibersortx. 
(5 random mixture matrices: 
![5mix](https://user-images.githubusercontent.com/62498686/123441849-a540a080-d617-11eb-9f63-8be6009bd8c6.png)
10 random mixture matrices:
![10mix](https://user-images.githubusercontent.com/62498686/123441895-b25d8f80-d617-11eb-8d45-1121f98c850b.png)
)
The macro-averaged MSE for a method is calculated as an average MSE of estimated cell proportions over 100 mixture matrices
![image](https://user-images.githubusercontent.com/62498686/123439085-b76d0f80-d614-11eb-9346-0c7cea3539f7.png)
![image](https://user-images.githubusercontent.com/62498686/123442649-737c0980-d618-11eb-95c8-dea12456cef9.png)

**Comment by Kamran-Khan96** [comment]
Resolved
